### ISSUE TITLE
Stopped working, error "Failed to get course ID"

### ISSUE THREAD

**Issue by Arduingo** [nishad/udemy-dl#1]
2 days ago the Script was working fine, now always show the error "Failed to get course ID"

**Comment by nishad** [comment]
Fixed with version`0.1.8`. Please update your script with
```bash
sudo pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master
```
:sake:

**Comment by Arduingo** [comment]
Thanks NIshad, confirmed its working

**Comment by HoLuong0211** [comment]
How can i run this cmd command "sudo pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master" on my window

**Comment by mukhlesur-millon** [comment]
for windows `python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master` @HoLuong0211
