### ISSUE TITLE
Install from pip

### ISSUE THREAD

**Issue by iFrey** [nishad/udemy-dl#10]
I made pip install udemy-dl , and it installed ok.
But it is outdated because it doesn't have this change yet https://github.com/nishad/udemy-dl/commit/fd340d1a508004f5b090f01592d2bdc61bf93ebd

**Comment by nishad** [comment]
`pip install udemy-dl` will install the legacy outdated version.

You need to install this new version via

```bash
sudo pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master
```
this is explained at https://github.com/nishad/udemy-dl/blob/master/README.md in **Install** section.
