### ISSUE TITLE
[BUG] Charmap

### ISSUE THREAD

**Issue by davecrouse** [nishad/udemy-dl#101]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

New Error.,

https://goo.gl/photos/rAKwT3Se65Fj5pLM8

I need help. When finished 1 video get ready to move on to the next video , the error . See accompanying figure will see the error . What should I do now?

If you need to get more videos to re-enter the command to be able to get more new videos .

Thanks

**Comment by nishad** [comment]
Please post your output of `udemy-dl -v`. As a temporary fix you can try with `--safe-file-names` option to avoid such glitches.

PS: Please edit and fill the checklists in your issue, that is mandate for this project.

**Comment by csjibna** [comment]
### Replicated with udemy-dl 0.2.1-beta

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\__main__.py", line 8, in <module>
    main()
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 813, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 700, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\site-packages\udemy_dl\udemy_dl.py", line 608, in get_data
    save_art.write(output_html)
  File "C:\Users\User\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 555-564: character maps to <undefined>


```

This error occurs only with one lecture in a set of more than sixty lectures. The lecture is somewhere near the middle.

As far as I can see, there are no unusual characters in the name of the lecture.

**Comment by davecrouse** [comment]
it deteled any and reinstall everything. Now it work but missing aria2. How can i install it? and can not pip install aria2. i use windows 7.

**Comment by nishad** [comment]
@davecrouse Please edit and fill the checklists in your issue, that is mandate for this project.

**Comment by mukhlesur-millon** [comment]
@csjibna please upgrade from [here](https://github.com/nishad/udemy-dl/wiki/Installing-development-version)

**Comment by csjibna** [comment]
Thank you MM. It now works fine, with or without **--safe-file-names**

Small bug. --video-quality 6 does not fall back on lower video qualities.

**Comment by mukhlesur-millon** [comment]
@csjibn [downloading lower video quality](https://github.com/nishad/udemy-dl/wiki/Downloading-lower-video-quality)

**Comment by nishad** [comment]
**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
