### ISSUE TITLE
[BUG] Not a downloadable course

### ISSUE THREAD

**Issue by rinodung** [nishad/udemy-dl#105]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

**OS: Window 7 with python 2.7**

**Step 1:** Install udemy-dl with:  pip install https://github.com/nishad/udemy-dl/zipball/master

**Step 2:** Login and Download Course: python udemy-dl.py https://www.udemy.com/the-complete-web-development-course-learn-by-building-apps

**Step 3:** **Error: not downloadable course**

![not a downloadable course](https://cloud.githubusercontent.com/assets/7805715/14983986/9b1db22c-116a-11e6-917a-3e70087efe15.PNG)

**Comment by nishad** [comment]
This issue is already answered a couple of times, (https://github.com/nishad/udemy-dl/issues?utf8=%E2%9C%93&q=Not+a+Downloadable+Course)

**Comment by rinodung** [comment]
Yes, It was a **closed issue**, but please confirm with me about downloading paid courses **without** buying these courses, currently I only download free course with udemy-dl script.

**Comment by egadgetjnr** [comment]
@rinodung 
Easy... Don't be a pirate! 
Read what you said, you want to download paid courses without paying for them? You're breaching Copyright and performing an illegal act and it's against Udemy and this Projects terms and conditions.......
