### ISSUE TITLE
[BUG] Youtube video attached stopped course download with error

### ISSUE THREAD

**Issue by javiermartingonzalez** [nishad/udemy-dl#109]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I want to download a course from Udemy today but failed with an error: (posted below).

How to replicate it:
1. Upgraded udemy-dl by using pip install --upgrade udemy-dl to make sure newest version is being used.
2. Use this command to download a Hadoop course: udemy-dl https://www.udemy.com/calculo-vectorial-practico. Insert Udemy login email and password.
3. Terminal prompts this message (after finished the download of 0017 video and trying to download an attach that is a link to Youtube video):

`Downloading attached files
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 706, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 624, in get_data
    get_attached_file(file_dir, attached_info)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 523, in get_attached_file
    for element in attached_json['download_urls']['File']:
KeyError: u'File'`

**Comment by mukhlesur-millon** [comment]
please run with `--debug` and post here the debug 
files.

**Comment by javiermartingonzalez** [comment]
Here you are the debug files.
[nishad-udemy-dl-3984cbc.zip](https://github.com/nishad/udemy-dl/files/266717/nishad-udemy-dl-3984cbc.zip)

**Comment by bharken** [comment]
This also happens to me every time there's an attachment (even if there's none available, I think). It's trying to download an attachment.

**Comment by mukhlesur-millon** [comment]
i have tried to fix it.
install:
`sudo python -m pip install https://github.com/mukhlesur-millon/udemy-dl/zipball/master -U`

**Comment by javiermartingonzalez** [comment]
This video is downloaded but there is another video with problem, exactly trying to download a Youtube video that is the 0039 of the course.

https://www.youtube.com/watch?v=MFcy1U0s4YY

[debug_udemy-dl.zip](https://github.com/nishad/udemy-dl/files/268288/debug_udemy-dl.zip)

**Comment by mukhlesur-millon** [comment]
i have updated the downloder.

**Comment by mukhlesur-millon** [comment]
`youtube-dl` automatically add `ext`.

**Comment by javiermartingonzalez** [comment]
Thank you! Installed youtube-dl and lecture download has been completed!

**Comment by mukhlesur-millon** [comment]
got it. it automatically add ext when ffmpeg is installed.
