### ISSUE TITLE
Download doesn't work anymore

### ISSUE THREAD

**Issue by mtedone** [nishad/udemy-dl#11]
Updated to the latest 0.1.18. 

I get the following: 
...
...
...
Cannot download lecture "Thank you for taking this course!"

Regards,

**Comment by rainbow99984** [comment]
Hi, download not working  i tried for error logs and it seems the download url of udemy has changed. current url format https://www.udemy.com/embed/<id> gives error  as 

Lec-id :<id> udemy_dl.py->parse_video_url
embed_url: https://www.udemy.com/embed/<id>
data 'None' returned by the regex. for jwplayer.
error "(<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'group'",), <traceback object at 0x7f6c0791cc68>)"
line number "116"
Cannot download lecture "<name of lecture> ?"
Thanks.

**Comment by mukhlesur-millon** [comment]
html = session.get(embed_url).text

i am also getting a 404 page in html

may be changes on

**Comment by Sulduzlu** [comment]
Cannot download lecture Sir!?!
Download links are changed! (I think)
Before links downloads from Akamai like this  Link: https://sknowbucket-a.akamaihd.net/2013-10-14_22-29-09-e1ece5d5151c24417daad579e350187e/WebHD_720p.mp4?__gda__=1405633330_e07dde57e3243969ac58e9e45f6b5f4d&filedownload=attachment
But now links download from udemy like this link : https://udemy-assets-on-demand.udemy.com/2015-08-22_17-11-54-e2ea85b3d0ff78c8446b7fde92e9e6cd/WebHD_720p.mp4?nva=20151229160132&token=0b2af792531b7f7c19be6
Changed from yesterday (I think)
Please Check & update your GOOD tool SIR , we wait for your UPDATE
Thanks for your attention.

**Comment by aleks-mariusz** [comment]
Looks like the parse_video_url() function will need to be overhaul'd to not rely on the /embed/ endpoint, as that is no longer available from udemy..

**Comment by tuchangwei** [comment]
Cannot download lecture...

**Comment by frankspin89** [comment]
Would be great if the script can be updated to match the new Udemy url structure.

**Comment by vladsolov** [comment]
hello , is there is any patch to fix the broken function?
Thanks for the project!

**Comment by feelingfree-me** [comment]
i'm create hotfix for this error try this :)
it have some issues i don't have time to fix it

https://github.com/feelingfree-me/udemy-dl

**Comment by vladsolov** [comment]
feelingfree-me : thanks a log but still not working; 
>udemy-dl -v
udemy-dl 0.1.8.1
udemy-dl ...
Cannot download lecture "..." //with no more info;

**Comment by bajeeshe** [comment]
iam getting following error while running latest code

--------------------
 get_url = 'https://www.udemy.com/api-2.0/users/me/subscribed-courses/542044/lectures/{0}?video_only=&auto_play=&fields[lecture]=asset,embed_url&fields[asset]=asset_type,download_urls,title&instructorPreviewMode=False'.format(lecture_id)
    json_source = session.get(get_url).json()
    print(json_source)
--------------------------

{'detail': 'You do not have permission to perform this action.'}

**Comment by mukhlesur-millon** [comment]
fix error
{'detail': 'You do not have permission to perform this action.'}
https://github.com/mukhlesur-millon/udemy-dl

**Comment by vanatomas** [comment]
did upgrade, still cannot download video

**Comment by vladsolov** [comment]
mukhlesur-millon thanks but for me it still no go; 
all files return with "Cannot download lecture ..."
should i print something at the code to make it report more info?

**Comment by tuchangwei** [comment]
Hi mukhlesur-millon,

If I should install the command using 'sudo pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/master' to replace  'sudo pip install --upgrade https://github.com/feelingfree-me/udemy-dl/zipball/master'

Thanks.

**Comment by tuchangwei** [comment]
Thanks to mukhlesur-millon, it works now.

I downloaded the source code from your repository, then ran "sudo pip install --upgrade ."

Now, I am downloading...

Thank you very much.

**Comment by mukhlesur-millon** [comment]
uninstall the previous one.
then
python -m pip install https://github.com/mukhlesur-millon/udemy-dl/zipball/master
then start it
python -m udemy_dl

**Comment by vladsolov** [comment]
mukhlesur-millon  u the MEN!!! ...working

**Comment by skyneteam** [comment]
Thanks mukhlesur-millon, I tried it and work fine, but some times in some courses appears this and break the download:

Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 220, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 161, in udemy_dl
    get_video(directory, filename, video['video_url'])
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 137, in get_video
    download(link, filename)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/download.py", line 11, in download
    if 'youtube.com' in link:
TypeError: argument of type 'NoneType' is not iterable

**Comment by mtedone** [comment]
Great stuff, it works. Closing the issue

**Comment by vineet-devin** [comment]
Can someone help me.. it says 
error: could not create '/Library/Python/2.7/site-packages/udemy_dl': Permission denied
im on mac

**Comment by vanatomas** [comment]
do sudo ....

**Comment by vineet-devin** [comment]
@vanatomas Awesome.. it worked! Thanks!

**Comment by vineet-devin** [comment]
Thank you @mukhlesur-millon . I was able to download the videos. But the quality of the videos is very bad. Any way I can improve the quality of it ?

**Comment by mukhlesur-millon** [comment]
if element['label'] == '1080':
                return element['file']
            elif element['label'] == '720':
                return element['file']
            elif element['label'] == '480':
                return element['file']
            elif element['label'] == '360':
                return element['file']

according to these line, it will download the highest quality...may be your course does not have high quality videos... you can comment the course url here...

**Comment by feelingfree-me** [comment]
@mukhlesur-millon it's fixed on my github

**Comment by vineet-devin** [comment]
@feelingfree-me OK i'll try the new one and revert.. thanks a lot

**Comment by tOlorun** [comment]
Hello guys

Please iam getting this error


Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 289, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, save_links)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 209, in udemy_dl
    for video in get_video_links(course_id, lecture_start, lecture_end):
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 126, in get_video_links
    course_data = session.get(course_url).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
