### ISSUE TITLE
[INVALID] Failed to get course ID

### ISSUE THREAD

**Issue by cking24343** [nishad/udemy-dl#112]
BUG 
Version : 2.0.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [X ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---
I keep getting an issue regarding the exe not able to find the course id: 

cmd:
C:\Users\xxxx\udemy-dl-win-2.0.1\udemy-dl-win>udemy-dl.exe -u xxxx@gmail.com -p xxxxxx https://www.udemy.com/quickstart-angularjs/learn/v4/t/lecture/1771832

Downloading to: C:\Users\xxxx\udemy-dl-win-2.0.1\udemy-dl-win\quickstart-angular js

Failed to get course ID

C:\Users\xxxx\udemy-dl-win-2.0.1\udemy-dl-win>

**Comment by tobias-p** [comment]
Hi cking

You are using the windows version of udemy-dl. That version isn't the latest version because - as I got it right from nishad - some other projects has to release a new version before the windows version can be updated.

In the wiki you can find a manual how to install the latest development version via python (which you have to install). After installing that version, you should be able to download the course.

Best wishes

**Comment by nishad** [comment]
According to your checklist, You have never used the project. And the issue raised is not related to this project. So this issue is invalid.
