### ISSUE TITLE
[INVALID] How to download specific Course Sections ?

### ISSUE THREAD

**Issue by soamz** [nishad/udemy-dl#115]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : 2.0.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [ X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ X] I have used the project briefly.
- [X ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I downloaded a course, which has 36 sections. After 15 section download, it has failed.
Now, I only need to download section 15 till section 36. 
What should be the full command format ?

Thanks.

**Comment by egadgetjnr** [comment]
Read the read me.
https://github.com/nishad/udemy-dl/blob/master/README.md

Look under advanced usage?

**Comment by soamz** [comment]
Checked advanced before posting, did not find the answer. 

I just need to download specific section to section, like section 15 to 36. 
so, need the command format.

**Comment by soamz** [comment]
--lecture-start LECTURE_START
                        Lecture to start at (default is 1)
  --lecture-end LECTURE_END
                        Lecture to end at (default is last)


I see this, but I guess its lecture time variable and not section variable.

**Comment by tobias-p** [comment]
for the sections, there is no extra variable... Just check, which is the last lecture you loaded (e.g. you stopped in section 15, lecture 63) then you use --lecture-start 64

**Comment by soamz** [comment]
F:\>udemy-dl.exe -u info@xxxxx.in -p xxxxxxx --lecture-start 53 --lecture-end 120 https://www.udemy.com/layer-2-switching-vlans/
Downloading to: F:\layer-2-switching-vlans

Failed to get course ID

F:\>

**Comment by tobias-p** [comment]
1. you dont need a lecture end, since you want to download the rest...
2. try this adress:  https://www.udemy.com/layer-2-switching-vlans/learn/v4

**Comment by mukhlesur-millon** [comment]
https://github.com/nishad/udemy-dl/issues/112#issuecomment-222841898

**Comment by soamz** [comment]
Still not able to do it :(
Its failing.

**Comment by nishad** [comment]
There is neither a 2.0.1 release nor a widows excecutable for this project. So this issue is invalid.

**Comment by soamz** [comment]
In github, I see 2 pages of this script. 
Both are yours or different ?
Looks like there is some confusion then, because as far as I know, you own both.

**Comment by tobias-p** [comment]
Both are owned by nishad, BUT the windows version gets slower the latest updates. I recommend you to use this version. In the wiki you find a Step-By-Step guide how to install and use this python version of udemy-dl on windows machines

**Comment by soamz** [comment]
Ahhhhh.. 
Its confusing. 
Python version, where do we install.

**Comment by tobias-p** [comment]
The guide can be found here: https://github.com/nishad/udemy-dl/wiki/Guide-for-install-and-use-of-the-udemy-dl-on-Windows

There is everything described.
