### ISSUE TITLE
HD videos

### ISSUE THREAD

**Issue by jaan143** [nishad/udemy-dl#116]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
hi Sir
its downloading HD 1920 x 1080 videos
but i want to download 1280 x 720 hd videos
is it possible ?

**Comment by tobias-p** [comment]
yeah, please read the reamde file on project side... In the advanced part, there are the commands, which you have to add

**Comment by jaan143** [comment]
where i can open .md files ?

**Comment by tobias-p** [comment]
you can rename it (since its is plain text), to a *.txt file ;) but I already added the most important infos for you in my first comment

**Comment by jaan143** [comment]
i got this one

**Comment by jaan143** [comment]
here 3241 is alias for 480p, 320p, 640p and 240p
and where is for 720p ?

**Comment by jaan143** [comment]
got solved 
plz close that 
thanks for your support

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
