### ISSUE TITLE
[QUESTION] Download multiple course only one login

### ISSUE THREAD

**Issue by valix85** [nishad/udemy-dl#118]
Hi guys, it's possible to execute a script for download/check multiple course?
udemy ban me for too many login in short time because for each course i run udemy-dl  -u username -p password course link.
Is possible pass a list of course or a file which have one course in every line?

Thank you
Best regards

**Comment by nishad** [comment]
There is a quick solution in https://github.com/nishad/udemy-dl/issues/9.

**Comment by tobias-p** [comment]
@nishad seems like this is not the solution the threadopener meant, since he god banned for using user login too often (as far as I got it)... so maybe this is a feature you could add

**Comment by nishad** [comment]
He should try with `--lecture-start` and `--lecture-end`, for downloading a course in multi-part. As we respect udemy policies, there is no intention to breach their login limitations.

**Comment by valix85** [comment]
can you write an example of your code please?

**Comment by jaan143** [comment]
valix85
here is full
python -m udemy_dl -u *******@yahoo.com -p ***** --lecture-start 5 --lecture-end 10 https://www.udemy.com/take-the-bulletproof-401k-super-charger-rat-race-off-ramp/

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
