### ISSUE TITLE
did'nt download Some Resource files

### ISSUE THREAD

**Issue by jaan143** [nishad/udemy-dl#121]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ X] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
HI SIR
plz check why its not downloading these files from Resource section
![udemy](https://cloud.githubusercontent.com/assets/15013833/16323721/6fb8509a-39c6-11e6-98cd-d92af9510656.JPG)

not only from this course
i checked many courses which have these type resource files

**Comment by mukhlesur-millon** [comment]
use the '--debug' option and post here the debug files.

**Comment by jaan143** [comment]
here is all Debug files

[DEBUG-get_course_data-20160624-060603.txt](https://github.com/nishad/udemy-dl/files/331778/DEBUG-get_course_data-20160624-060603.txt)

[DEBUG-get_json_source-20160624-060603.txt](https://github.com/nishad/udemy-dl/files/331779/DEBUG-get_json_source-20160624-060603.txt)
[DEBUG-get_json_source-20160624-060604.txt](https://github.com/nishad/udemy-dl/files/331780/DEBUG-get_json_source-20160624-060604.txt)
[DEBUG-get_json_source-20160624-060605.txt](https://github.com/nishad/udemy-dl/files/331782/DEBUG-get_json_source-20160624-060605.txt)
[DEBUG-get_json_source-20160624-060606.txt](https://github.com/nishad/udemy-dl/files/331781/DEBUG-get_json_source-20160624-060606.txt)
[DEBUG-get_json_source-20160624-060607.txt](https://github.com/nishad/udemy-dl/files/331783/DEBUG-get_json_source-20160624-060607.txt)
[Uploading DEBUG-get_json_source-20160624-060608.txt…]()
[DEBUG-get_json_source-20160624-060609.txt](https://github.com/nishad/udemy-dl/files/331784/DEBUG-get_json_source-20160624-060609.txt)

**Comment by mukhlesur-millon** [comment]
`sudo python -m pip install --upgrade http://github.com/nishad/udemy-dl/zipball/master` upgrade your udemy-dl and try again. Your are using old version.

**Comment by jaan143** [comment]
i updated now and its downloading many DEBUG files in first section and inside that file have only these words
{'id': 3204104, 'download_urls': None, '_class': 'asset'}

**Comment by mukhlesur-millon** [comment]
zip the debug files and post here.

**Comment by jaan143** [comment]
zip file is not uploading here its giving error then i upload each file
[DEBUG-attached_file_3204098-20160624-191150.txt](https://github.com/nishad/udemy-dl/files/332733/DEBUG-attached_file_3204098-20160624-191150.txt)
[DEBUG-attached_file_3204102-20160624-191151.txt](https://github.com/nishad/udemy-dl/files/332735/DEBUG-attached_file_3204102-20160624-191151.txt)
[DEBUG-attached_file_3204104-20160624-191152.txt](https://github.com/nishad/udemy-dl/files/332734/DEBUG-attached_file_3204104-20160624-191152.txt)
[DEBUG-attached_file_3204106-20160624-191153.txt](https://github.com/nishad/udemy-dl/files/332736/DEBUG-attached_file_3204106-20160624-191153.txt)
[DEBUG-attached_file_3204112-20160624-191154.txt](https://github.com/nishad/udemy-dl/files/332738/DEBUG-attached_file_3204112-20160624-191154.txt)
[DEBUG-attached_file_3204116-20160624-191155.txt](https://github.com/nishad/udemy-dl/files/332737/DEBUG-attached_file_3204116-20160624-191155.txt)
[DEBUG-attached_file_3204120-20160624-191156.txt](https://github.com/nishad/udemy-dl/files/332739/DEBUG-attached_file_3204120-20160624-191156.txt)
[DEBUG-attached_file_3204126-20160624-191158.txt](https://github.com/nishad/udemy-dl/files/332740/DEBUG-attached_file_3204126-20160624-191158.txt)
[DEBUG-attached_file_3204128-20160624-191159.txt](https://github.com/nishad/udemy-dl/files/332742/DEBUG-attached_file_3204128-20160624-191159.txt)
[DEBUG-attached_file_3204132-20160624-191200.txt](https://github.com/nishad/udemy-dl/files/332741/DEBUG-attached_file_3204132-20160624-191200.txt)
[DEBUG-attached_file_3204138-20160624-191201.txt](https://github.com/nishad/udemy-dl/files/332743/DEBUG-attached_file_3204138-20160624-191201.txt)
[DEBUG-attached_file_3204140-20160624-191202.txt](https://github.com/nishad/udemy-dl/files/332744/DEBUG-attached_file_3204140-20160624-191202.txt)
[DEBUG-attached_file_3204142-20160624-191202.txt](https://github.com/nishad/udemy-dl/files/332745/DEBUG-attached_file_3204142-20160624-191202.txt)
[DEBUG-attached_file_3204144-20160624-191202.txt](https://github.com/nishad/udemy-dl/files/332746/DEBUG-attached_file_3204144-20160624-191202.txt)

**here is second section folder's debug files**
[DEBUG-attached_file_3204170-20160624-191316.txt](https://github.com/nishad/udemy-dl/files/332750/DEBUG-attached_file_3204170-20160624-191316.txt)
[DEBUG-attached_file_3204172-20160624-191316.txt](https://github.com/nishad/udemy-dl/files/332749/DEBUG-attached_file_3204172-20160624-191316.txt)
[DEBUG-attached_file_3204176-20160624-191844.txt](https://github.com/nishad/udemy-dl/files/332751/DEBUG-attached_file_3204176-20160624-191844.txt)
[DEBUG-attached_file_3204180-20160624-191844.txt](https://github.com/nishad/udemy-dl/files/332753/DEBUG-attached_file_3204180-20160624-191844.txt)
[DEBUG-attached_file_3204190-20160624-191933.txt](https://github.com/nishad/udemy-dl/files/332752/DEBUG-attached_file_3204190-20160624-191933.txt)
[DEBUG-attached_file_3204194-20160624-191933.txt](https://github.com/nishad/udemy-dl/files/332754/DEBUG-attached_file_3204194-20160624-191933.txt)
[DEBUG-attached_file_3204198-20160624-191934.txt](https://github.com/nishad/udemy-dl/files/332755/DEBUG-attached_file_3204198-20160624-191934.txt)
[DEBUG-attached_file_3204202-20160624-191934.txt](https://github.com/nishad/udemy-dl/files/332756/DEBUG-attached_file_3204202-20160624-191934.txt)
[DEBUG-attached_file_3204210-20160624-191934.txt](https://github.com/nishad/udemy-dl/files/332757/DEBUG-attached_file_3204210-20160624-191934.txt)
[DEBUG-attached_file_3204216-20160624-191935.txt](https://github.com/nishad/udemy-dl/files/332758/DEBUG-attached_file_3204216-20160624-191935.txt)
[DEBUG-attached_file_3204218-20160624-192026.txt](https://github.com/nishad/udemy-dl/files/332759/DEBUG-attached_file_3204218-20160624-192026.txt)
[DEBUG-attached_file_3204222-20160624-192026.txt](https://github.com/nishad/udemy-dl/files/332760/DEBUG-attached_file_3204222-20160624-192026.txt)
[DEBUG-attached_file_3204224-20160624-192027.txt](https://github.com/nishad/udemy-dl/files/332761/DEBUG-attached_file_3204224-20160624-192027.txt)
[DEBUG-attached_file_3292588-20160624-191317.txt](https://github.com/nishad/udemy-dl/files/332762/DEBUG-attached_file_3292588-20160624-191317.txt)

**Comment by mukhlesur-millon** [comment]
`ExternalLink` in `supplementary_assets` was intentionally skipped because it can be anything. some link from your course:
- video: https://www.youtube.com/watch?v=!!!!!!!!!!!!!!!!!
- ms support: https://support.microsoft.com/en-us/kb/982954
- download link (not direct): http://mediaarea.net/en/MediaInfo/Download
- youtube link: https://www.youtube.com/my_videos?o=U
- google support: https://support.google.com/youtube/answer/2887282?hl=en
- article link: http://cypressnorth.com/search-engine-marketing/add-external-links-youtube-video-annotations/
- ....

**Comment by mukhlesur-millon** [comment]
`ExternalLink` in `supplementary_assets` was intentionally skipped because it can be anything. some link from your course:
- video: https://www.youtube.com/watch?v=!!!!!!!!!!!!!!!!!
- ms support: https://support.microsoft.com/en-us/kb/982954
- download link (not direct): http://mediaarea.net/en/MediaInfo/Download
- youtube link: https://www.youtube.com/my_videos?o=U
- google support: https://support.google.com/youtube/answer/2887282?hl=en
- article link: http://cypressnorth.com/search-engine-marketing/add-external-links-youtube-video-annotations/
- ....

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by jaan143** [comment]
so now we cant download these type files from udemy-dl ?

**Comment by egadgetjnr** [comment]
*All issues should contain mandatory check lists, version number and proper
prefix for the subject line. Issues reported without checklists, version or
without proper prefix will be closed or ignored.*
