### ISSUE TITLE
[PROPOSAL] -  Support download subtitle

### ISSUE THREAD

**Issue by lephuongbac** [nishad/udemy-dl#126]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hello,

I just want to download subtitle of video if it's available. File name will be the same with video file name.

Thanks.

**Comment by nishad** [comment]
Closed Caption aka Subtitle support is already enabled with https://github.com/nishad/udemy-dl/pull/94. Kudos to @mukhlesur-millon for this outstanding PR. If there are subtitles available for a video, it will be downloaded automatically.

**Comment by francyfre** [comment]
subtitle's video dont download... in the videos there is subtitle
but, when i finish download... there is no!!!! 

i want to ask because in youtube.dl there is --all-subs option that dont functions in udemy-dl

i need subtitle, please! 

francesco
