### ISSUE TITLE
[BUG] cannot download, getting  [CRITICAL-407] Cannot download error!

### ISSUE THREAD

**Issue by SKYLOR7** [nishad/udemy-dl#129]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ X] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{I'm having this issue x% [====================] [CRITICAL-407] Cannot download lecture 
non of my paid course contents had been downloaded }

**Comment by davecrouse** [comment]
Same problem. How can we fix. Help me please. Thanks

**Comment by 7ang** [comment]
Me too. :-(

**Comment by jackhai9** [comment]
same bug

**Comment by samg86** [comment]
you can work around this by editing around line 231 in udemy_dl.py to be:

            try:
                quality = re.match(r'.*/hls_audio_(\d+)', line).group(1)
            except:
                quality = re.match(r'.*/hls_(\d+)_', line).group(1)

It worked for me anyway.

**Comment by martinserafim93** [comment]
Yo! ty samg86. It work!

**Comment by nishad** [comment]
This issue is already addressed in development version `0.2.2-alpha`.

**Comment by narender-thakur** [comment]
Thanks @samg86 its worked.
