### ISSUE TITLE
[BUG] Failed to get course ID when downloading course

### ISSUE THREAD

**Issue by proxymoron** [nishad/udemy-dl#131]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Version : udemy-dl-0.2.1

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.  Similar issue has been reported for downloading individual lectures, however.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I've previously used the tool to download my plethora of purchased courses on Udemy.  However, now whenever I attempt, I am faced with the "Failed to get course ID" error whenever I attempt to download a course.

My log in details have not changed, I am using the most up to date versions of udemy-dl (0.2.1) and Python (3.5).  I even downloaded and instealled Pandoc.

```
C:\Users\xxx\Downloads\udemy-dl-windows-master\udemy-dl-windows-master\dist>udemy-dl.exe https://www.udemy.com/java-the-complete-java-developer-course/
Username/Email: my_email@gmail.com
Password:
Downloading to: C:\Users\xxx\Downloads\udemy-dl-windows-master\udemy-dl-windows-master\dist\java-the-complete-java-developer-course

Failed to get course ID
```

Admitedly it's been a few months since using the application but I don't see why this is failing.  I've previously used this to download some 100+ course I've purchased on Udemy over time.

**Comment by mukhlesur-millon** [comment]
https://github.com/nishad/udemy-dl/wiki/Guide-for-install-and-use-of-the-udemy-dl-on-Windows

**Comment by proxymoron** [comment]
Hey
Yeah, that's how I installed it and ran it on my new machine.

**Comment by nishad** [comment]
This issue is not related with this project.
