### ISSUE TITLE
[PROPOSAL] requirement should be `python-pptx`

### ISSUE THREAD

**Issue by bookletchoir** [nishad/udemy-dl#135]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [x] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Short story, the requirement should be [python-pptx](https://pypi.python.org/pypi/python-pptx) instead of [pptx](https://github.com/nishad/udemy-dl/blob/master/requirements.txt#L5).

I ran into installation problem on python 3.5.2 with pip (latest commit of udemy-dl, up to now):
```
➜  ~  pip install git+git://github.com/nishad/udemy-dl.git 
[...]
Collecting pptx (from udemy-dl==0.2.1)
  Could not find a version that satisfies the requirement pptx (from udemy-dl==0.2.1) (from versions: )
No matching distribution found for pptx (from udemy-dl==0.2.1)
```

**Comment by mukhlesur-millon** [comment]
yes...my mistake.

@nishad please change the line.
