### ISSUE TITLE
cant install new version

### ISSUE THREAD

**Issue by jaan143** [nishad/udemy-dl#139]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hi Sir
i am trying to install new version 2.1.1 but when i use upgrade command its upgraded but when i check version its shows old version here you can check
plz tell me how can i upgrade version to 2.1.1

PS C:\Users\vicky> python -m pip install --upgrade udemy_dl
Requirement already up-to-date: udemy_dl in c:\python34\lib\site-packages
Requirement already up-to-date: requests in c:\python34\lib\site-packages (from udemy_dl)
Requirement already up-to-date: unicode-slugify in c:\python34\lib\site-packages (from udemy_dl)
Requirement already up-to-date: colorlog in c:\python34\lib\site-packages (from udemy_dl)
Requirement already up-to-date: future in c:\python34\lib\site-packages (from udemy_dl)
Requirement already up-to-date: six in c:\python34\lib\site-packages (from unicode-slugify->udemy_dl)
Requirement already up-to-date: unidecode in c:\python34\lib\site-packages (from unicode-slugify->udemy_dl)
Requirement already up-to-date: colorama; sys_platform == "win32" in c:\python34\lib\site-packages (from colorlog->udemy_dl)
PS C:\Users\vicky> python -m udemy_dl --version
udemy-dl 0.2.1
PS C:\Users\vicky>

thanks

**Comment by nishad** [comment]
This projects latest version is 0.2.1. There isn't 2.1.1 yet.
