### ISSUE TITLE
 Output directory - create default directory

### ISSUE THREAD

**Issue by madmax2** [nishad/udemy-dl#145]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I use -o to save udemy course e.g https://www.udemy.com/taking-action/learn/v4/overview 
to C:\Udemy.

But the problem is I would like it to save it to the default course name instead of just C:\Udemy.
e.g. C:\Udemy\taking-action
This way, I don't need to go into that C:\Udemy and create a new directory "taking-action" and move those downloaded files to it, since the default course name directory was already created.

Can you please add a feature/command line argument to let me do this...

BTW how to update to 0.2.2-alpha?
I tried this python -m pip install --upgrade udemy-dl but it is still showing my version as 0.2.1.

**Comment by egadgetjnr** [comment]
@madmax2 try using `pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master`

**Comment by madmax2** [comment]
@egadgetjnr I did this and it seems to show upgraded e.g. Collecting lxml>=3.1.0 (from python-pptx->udemy-dl==0.2.2a0)
but when I go to my python directory e.g. C:\Python\Python352-32\Scripts
and I type python udemy-dl -v, it shows udemy-dl 0.2.1

**Comment by egadgetjnr** [comment]
@madmax2, that should be fine. Just check the instructions on how to use
the new feature, but the command is '--dir--use-course-title' I believe.

**Comment by madmax2** [comment]
@egadgetjnr how to use "--use-course-title" in the argument.. with -O 
I get error 
udemy-dl: error: unrecognized arguments: --use-course-title

please test and post full command line with arguments.

On the front page, there is no argument "--dir--use-course-title"

**Comment by egadgetjnr** [comment]
@madmax2 My apologies. I'm still fairly new to Python and didn't know that the argument `--dir--use-course-title` was wrong (sorry @nishad!) 

Try using this command for that course you're wanting to get
`python -m udemy_dl --use-course-title -o C:\Udemy\ https://www.udemy.com/taking-action/learn/v4/overview`

**Comment by madmax2** [comment]
@egadgetjnr actually I checked and there is some incorrect information on the front page

In advance usage section there is this:

usage: udemy-dl [-h] [-u USERNAME] [-p PASSWORD]
                [--lecture-start LECTURE_START] [--lecture-end LECTURE_END]
                [-o OUTPUT] [-d {aria2c,axel,httpie,curl}] [--use-ffmpeg]
                [-q VIDEO_QUALITY] [-s] [--safe-file-names] [-l] [--debug] **[--dir--use-course-title]**
                [-v]
                link

option arguments
 **--use-course-title    Use the course title for the parent folder name (WARNING: can make file path too long**

**Comment by egadgetjnr** [comment]
@madmax2, I'll fix that up.

It should just be `--use-course-title`

**Comment by madmax2** [comment]
@egadgetjnr did u test the command u posted? Cos I tested it and go an error udemy-dl: error: unrecognized arguments: --use-course-title

**Comment by nishad** [comment]
Fixed with latest development release, https://github.com/nishad/udemy-dl/commit/4c01eebe14c7063bfbbcca113535c9f074e8907d.
