### ISSUE TITLE
Couldn't upgrade to  0.2.2v currently on 0.2.1

### ISSUE THREAD

**Issue by SKYLOR7** [nishad/udemy-dl#151]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ x] I have checked that the issue I'm posting isn't already reported.
- [ x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

**Comment by SKYLOR7** [comment]
getting this error while trying to update udemy-dl 

> HTTP error 404 while getting https://github.com/mukhlesur-millon/udemy-dl/zipball/master
  Could not install requirement https://github.com/mukhlesur-millon/udemy-dl/zipball/master because of error 404 Client Error: Not Found for url: https://github.com/mukhlesur-millon/udemy-dl/zipball/master
Could not install requirement https://github.com/mukhlesur-millon/udemy-dl/zipball/master because of HTTP error 404 Client Error: Not Found for url: https://github.com/mukhlesur-millon/udemy-dl/zipball/master for URL https://github.com/mukhlesur-millon/udemy-dl/zipball/master
> 

I've tried to update it through 
pip install --upgrade udemy-dl
and so other methods but i keep having version 0.2.1 

thanks 💯

**Comment by nishad** [comment]
Refer the project wiki

**Comment by SKYLOR7** [comment]
thanks
