### ISSUE TITLE
[BUG] Can't update to latest development version 0.2.2-alpha

### ISSUE THREAD

**Issue by madmax2** [nishad/udemy-dl#155]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**
- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**
- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**
- No additional requirements.

---

{issue content here, replace this line with your issue content}
I tried to upgrade to 0.2.2-alpha using this command
pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master

Why is the version check still showing 0.21

> udemy-dl -v = udemy-dl 0.2.1

**Comment by nishad** [comment]
Seems like the upgrade to development version is failing. Could you try again and post the output for the command.

```
pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master
```

**Comment by madmax2** [comment]
@nishad 

Collecting https://github.com/nishad/udemy-dl/zipball/master
  Downloading https://github.com/nishad/udemy-dl/zipball/master
Requirement already up-to-date: requests in c:\python\python352-32\lib\site-packages (from udemy-dl==0.2.2a0)
Requirement already up-to-date: unicode-slugify in c:\python\python352-32\lib\site-packages (from udemy-dl==0.2.2a0)
Requirement already up-to-date: colorlog in c:\python\python352-32\lib\site-packages (from udemy-dl==0.2.2a0)
Requirement already up-to-date: future in c:\python\python352-32\lib\site-packages (from udemy-dl==0.2.2a0)
Collecting python-pptx (from udemy-dl==0.2.2a0)
  Using cached python-pptx-0.6.0.tar.gz
Requirement already up-to-date: six in c:\python\python352-32\lib\site-packages (from unicode-slugify->udemy-dl==0.2.2a0)
Requirement already up-to-date: unidecode in c:\python\python352-32\lib\site-packages (from unicode-slugify->udemy-dl==0.2.2a0)
Requirement already up-to-date: colorama; sys_platform == "win32" in c:\python\python352-32\lib\site-packages (from colorlog->udemy-dl==0.2.2a0)
Collecting lxml>=3.1.0 (from python-pptx->udemy-dl==0.2.2a0)
  Using cached lxml-3.6.4.tar.gz
Collecting Pillow>=2.6.1 (from python-pptx->udemy-dl==0.2.2a0)
  Using cached Pillow-3.4.1-cp35-cp35m-win32.whl
Collecting XlsxWriter>=0.5.7 (from python-pptx->udemy-dl==0.2.2a0)
  Using cached XlsxWriter-0.9.3-py2.py3-none-any.whl
Installing collected packages: lxml, Pillow, XlsxWriter, python-pptx, udemy-dl
  Running setup.py install for lxml ... error
    Complete output from command c:\python\python352-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\TYLER~1.DUR\\AppData\\Local\\Temp\\pip-build-l9bu7ia3\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\TYLER~1.DUR\AppData\Local\Temp\pip-l_goy08b-record\install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.6.4.
    Building without Cython.
    ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    creating build\lib.win32-3.5\lxml
    copying src\lxml\builder.py -> build\lib.win32-3.5\lxml
    copying src\lxml\cssselect.py -> build\lib.win32-3.5\lxml
    copying src\lxml\doctestcompare.py -> build\lib.win32-3.5\lxml
    copying src\lxml\ElementInclude.py -> build\lib.win32-3.5\lxml
    copying src\lxml\pyclasslookup.py -> build\lib.win32-3.5\lxml
    copying src\lxml\sax.py -> build\lib.win32-3.5\lxml
    copying src\lxml\usedoctest.py -> build\lib.win32-3.5\lxml
    copying src\lxml\_elementpath.py -> build\lib.win32-3.5\lxml
    copying src\lxml\__init__.py -> build\lib.win32-3.5\lxml
    creating build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\__init__.py -> build\lib.win32-3.5\lxml\includes
    creating build\lib.win32-3.5\lxml\html
    copying src\lxml\html\builder.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\clean.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\defs.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\diff.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\ElementSoup.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\formfill.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\html5parser.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\soupparser.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\usedoctest.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\_diffcommand.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\_html5builder.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\_setmixin.py -> build\lib.win32-3.5\lxml\html
    copying src\lxml\html\__init__.py -> build\lib.win32-3.5\lxml\html
    creating build\lib.win32-3.5\lxml\isoschematron
    copying src\lxml\isoschematron\__init__.py -> build\lib.win32-3.5\lxml\isoschematron
    copying src\lxml\lxml.etree.h -> build\lib.win32-3.5\lxml
    copying src\lxml\lxml.etree_api.h -> build\lib.win32-3.5\lxml
    copying src\lxml\includes\c14n.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\config.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\dtdvalid.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\etreepublic.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\htmlparser.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\relaxng.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\schematron.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\tree.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\uri.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\xinclude.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\xmlerror.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\xmlparser.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\xmlschema.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\xpath.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\xslt.pxd -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\etree_defs.h -> build\lib.win32-3.5\lxml\includes
    copying src\lxml\includes\lxml-version.h -> build\lib.win32-3.5\lxml\includes
    creating build\lib.win32-3.5\lxml\isoschematron\resources
    creating build\lib.win32-3.5\lxml\isoschematron\resources\rng
    copying src\lxml\isoschematron\resources\rng\iso-schematron.rng -> build\lib.win32-3.5\lxml\isoschematron\resources\rng
    creating build\lib.win32-3.5\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\RNG2Schtrn.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl
    copying src\lxml\isoschematron\resources\xsl\XSD2Schtrn.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl
    creating build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_abstract_expand.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_dsdl_include.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_message.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_schematron_skeleton_for_xslt1.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\iso_svrl_for_xslt1.xsl -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    copying src\lxml\isoschematron\resources\xsl\iso-schematron-xslt1\readme.txt -> build\lib.win32-3.5\lxml\isoschematron\resources\xsl\iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

    ----------------------------------------
Command "c:\python\python352-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\TYLER~1.DUR\\AppData\\Local\\Temp\\pip-build-l9bu7ia3\\lxml\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\TYLER~1.DUR\AppData\Local\Temp\pip-l_goy08b-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\TYLER~1.DUR\AppData\Local\Temp\pip-build-l9bu7ia3\lxml\

**Comment by madmax2** [comment]
Version check still shows
>python C:\Python\Python352-32\Scripts\udemy-dl -v

udemy-dl 0.2.1

**Comment by tobias-p** [comment]
Damn madmax.... If you would read just a little bit, you would see, that the update didnt install because you are missing this: ** make sure the development packages of libxml2 and libxslt are installed **

Installing libxml2 should solve the problem. How to install it is mentioned here: https://github.com/nishad/udemy-dl/issues/147

Don't know how to mark directly the answer, so you have to scroll down to an answer nishad did on 3rd September.

**Comment by madmax2** [comment]
@tobias-p 
excuse me, but there was a lot of output message and not everyone understands that there was an error message or if it means anything...

**Comment by tobias-p** [comment]
You are using Python 352-32 which means 3.52 32bit and tried to install the cp34 (for Python 3.4x) and cp35 for 64bit... find the error yourself.

download the one called lxml-3.6.4-cp35-cp35m-win32.whl and the installation will be fine...

**Comment by madmax2** [comment]
@tobias-p 
I only copied it here because it was requested..
the intial output screen of messages was very long as you can tell by the post here..
lots of messages, it's not easy to to discern what is the error or even what the error means..

i didn't say it was the only reason..it was just one of the reason..

i am just a noob with python and still learning..and just know how to use this script and a few basic commands.. 
Like you can see here, i don't even know why i couldn't install that wheel until you posted the error..

so just take it easy

Everyone was a noob once..

Anyway, thanks for the solutions
It is now upgraded 0.2.2-alpha.
