### ISSUE TITLE
udemy-dl doesn't work at all with me

### ISSUE THREAD

**Issue by hatahetahmad** [nishad/udemy-dl#156]
I installed Python 2.7 then Add new Environment to windows called "PATH"
"PATH =  C:\Python27;C:\Python27\Scripts"

Then Run Windows Power Shell as admin
Type this "pip install udemy-dl"

when finish I tried typing "udemy-dl -u ## -p ** http://www.udemy-course-url"

downloading failed
and **error as image down**

![2016-10-03_21-02-50](https://cloud.githubusercontent.com/assets/22600982/19210315/f1333908-8d1f-11e6-8a47-b508c0fd03e3.png)

then i tried to upgrade Udemy-dl to newest version
and tried to download my course but didn't work
and I got error "**Critical-407**" and Downloaded only attachment pdfs

then I closed Power Shall and Open it again and type same command "udemy-dl -u ## -p ** http://www.udemy-course-url"

I Got this :
#!c:\python27\python.exe
from __future__ import unicode_literals
from __future__ import print_function

if __name__ == '__main__':
    from udemy_dl.udemy_dl import main
    main()

I downloaded a ZIP that "udemy-dl-windows-master" but i didn't know how to use it and where to unzip it

I don't know what to do, I was using youtube-dl and working fine but I want to download Courses attachment and real video title by using udemy-dl

this the course I've been trying to downloaded
"https://www.udemy.com/how-to-create-internet-stores-the-easy-way-using-wordpress/learn/v4/content"

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
