### ISSUE TITLE
[ERROR-1198] Traceback (most recent call last)

### ISSUE THREAD

**Issue by grohit19** [nishad/udemy-dl#159]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **2.12**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ x] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm posting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [x ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

E:\Applications\nishad-udemy-dl-windows-v2.1.2-0-g10a95b3\nishad-udemy-dl-window
s-10a95b3\dist>udemy-dl.exe -u g.r*********@gmail.com -p **************** https://
www.udemy.com/course-dashboard-redirect/?course_id=446710
[INFO-884] Downloading to: E:\Applications\nishad-udemy-dl-windows-v2.1.2-0-g10a
95b3\nishad-udemy-dl-windows-10a95b3\dist\course-dashboard-redirect

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: logo.jpg
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
KeyError: u'results'
None
udemy_dl returned -1

**Comment by tobias-p** [comment]
on first sight, maybe your course link is wrong?

**Comment by nishad** [comment]
Agrees with @tobias-p, course link is wrong.

**Comment by altamiranoesdras** [comment]
[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 763172
Getting course data: 100.00% [====================] Done


Downloading Video: 001 Introducción al curso

[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 648, in get_data
  File "<string>", line 586, in get_video
  File "<string>", line 621, in check_downloaded
  File "download.py", line 38, in download
  File "download.py", line 86, in ffmpeg_dl
  File "subprocess.py", line 522, in call
  File "subprocess.py", line 710, in __init__
  File "subprocess.py", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 424: ordinal not in range(128)
None
udemy_dl returned -1

**Comment by altamiranoesdras** [comment]
Please install "ffmpeg" and use argument "--use-ffmpeg"

how to install?

**Comment by grohit19** [comment]
Hello nishad,
  

  
I had found that probably URL I put was not correct. I was able to fix it.   
    
  
  
 Thanks  &  Regards G Rohit  

  

  
  
  
  

  
  
>

**Comment by manthankool** [comment]
grohit how did u found that URL , because i am also facing the same problem

**Comment by grohit19** [comment]
@manthankool - what's your course name ? N what's the URL of the page on which you see your course n it's content ?

**Comment by bossyahrul** [comment]
@grohit19 can you help me ? this is my course name
Ultimate React Native - Easily Build iOS and Android Apps
and here's the link https://www.udemy.com/ultimate-react-native-easily-build-ios-and-android-apps/

**Comment by santhoshmalla** [comment]
Can you help me ?
1st course download was succesfull,but when i am trying to download second one i am facing an issue
 File "udemy_dl.py", line 976, in <module>
  File "udemy_dl.py", line 971, in main
  File "udemy_dl.py", line 785, in udemy_dl
  File "udemy_dl.py", line 431, in get_data_links
KeyError: u'results'
Please help me out

**Comment by bossyahrul** [comment]
Sorry I'm not the expert in this case

Maybe for the complete solution you can contact gr.data19@gmail.com

He has solved my udemy dl problem too :)
