### ISSUE TITLE
[BUG] CRITICAL-46 Downloaded Video Won't Play Properly

### ISSUE THREAD

**Issue by ninobc** [nishad/udemy-dl#172]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.2-alpha**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [X] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hello everyone. 

I just started using this tool in order to download Udemy courses, updated the version to 0.2.2-alpha in order to fix the CRITICAL-407 issue, and all seems to be working fine. However, as the downloading parts of a lecture get combined, a new MP4 file is created and when I play it everything seems to be working fine. But if i try to navigate through the video it stops playing and a gray screen appears! Any help would be really appreciated. 

P.S: while downloading, it says [CRITICAL-46] aria2c not found. Downloading with builtin downloader.

Also, the media player used in VLC, the file won't open on QuickTIme

**Comment by mzgnr** [comment]
@ninobc Hi, if you are on macOS can you try ` brew install aria2 ffmpeg `

**Comment by ninobc** [comment]
@mzgnr Hi, thank you for your reply! I am on macOS and not quite sure how to execute the command you sent me. I tried typing "brew install aria2 ffmpeg" into the terminal and i got "brew: command not found". I apologize for asking such questions, but quite new to this.

**Comment by mzgnr** [comment]
@ninobc you need to install https://github.com/Homebrew/brew/

**Comment by ninobc** [comment]
@mzgnr just figured that out also. Will do it and get back to you asap.

**Comment by ninobc** [comment]
@mzgnr I just finished installing it. should i try and download a lecture and check if the issue is solved?

**Comment by mzgnr** [comment]
@ninobc you should. but please take a look at the readme.

**Comment by ninobc** [comment]
@mzgnr I am running through the same issue. The warning is no longer there. But when the parts are done downloading and patched up into the mp4 file, once I try to navigate through the video a gray screen comes and the video no longer plays. I think it has something to do with the patching of the downloaded parts. each part is downloading as a 2.5MB packet then stitched up into an mp4 file. Is that the normal procedure of the script or is there something else causing the problem?

Thank you so much for your support, I truly appreciate it.

**Comment by ninobc** [comment]
i.e. is there a way I can download the whole lecture as a single file, instead of downloading 2.5MB files then stitching them up into the original file?

**Comment by mzgnr** [comment]
Did you try with --use-ffmpeg flag ? And also use VLC

**Comment by ninobc** [comment]
@mzgnr I don't know how to thank u! it worked! Thank you for all of your help. Much appreciated. And I feel bad for not trying the above flag, although I thought about it.
