### ISSUE TITLE
[ERROR-1198] Traceback (most recent call last)

### ISSUE THREAD

**Issue by altamiranoesdras** [nishad/udemy-dl#175]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

udemy-dl -u xxxxx@gmail.com -p ***** https://www.udemy.com/curso-de-cpp-basico-a-avanzado --use-ffmpeg

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 763172
Getting course data: 100.00% [====================] Done

Downloading Video: 001 Introducción al curso

[ERROR-1198] Traceback (most recent call last):
File "", line 889, in
File "", line 886, in main
File "", line 745, in udemy_dl
File "", line 648, in get_data
File "", line 586, in get_video
File "", line 621, in check_downloaded
File "download.py", line 38, in download
File "download.py", line 86, in ffmpeg_dl
File "subprocess.py", line 522, in call
File "subprocess.py", line 710, in init
File "subprocess.py", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 424: ordinal not in range(128)
None
udemy_dl returned -1

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
