### ISSUE TITLE
[Bug] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 35: ordinal not in range(128)

### ISSUE THREAD

**Issue by diegobassan** [nishad/udemy-dl#182]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **2.1.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [X] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

```
Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
Error in sys.excepthook:
Traceback (most recent call last):
  File "<string>", line 55, in logging_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 35: ordinal not in range(128)

Original exception was:

Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 648, in get_data
  File "<string>", line 607, in get_video
  File "<string>", line 623, in check_downloaded
WindowsError: [Error 2] O sistema nÒo pode encontrar o arquivo especificado
udemy_dl returned -1
```

**Comment by tahitibub** [comment]
Same problem. Bug confirmed (with French language files names).

**Comment by nishad** [comment]
Fixed with https://github.com/nishad/udemy-dl/commit/165841a5b15767f78dee8e551855cbc1d77a84a7, use the latest development version and let me know the result.
