### ISSUE TITLE
[BUG] Cannot download course if German umlauts are in course

### ISSUE THREAD

**Issue by mfechner** [nishad/udemy-dl#199]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **2.1.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported. (Similar requests existing, but they seem not to be related)
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Downloading course with none ascii characters is not working.
Downloading the course is showing:
```
[INFO-884] Downloading to: D:\owncloud\mydomain\udemy-videos\suchmaschinenoptimierung-lernen

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 939110
Getting course data: 100.00% [====================] Done


Downloading Video: 001 SEO einfach erklärt

[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 745, in udemy_dl
  File "<string>", line 648, in get_data
  File "<string>", line 607, in get_video
  File "<string>", line 621, in check_downloaded
  File "download.py", line 30, in download
  File "download.py", line 80, in aria2c_dl
  File "subprocess.py", line 522, in call
  File "subprocess.py", line 710, in __init__
  File "subprocess.py", line 958, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 355: ordinal not in range(128)
None
udemy_dl returned -1
```

**Comment by nishad** [comment]
Could you try with `--safe-file-names` and let me know the result ?

**Comment by nishad** [comment]
Fixed with https://github.com/nishad/udemy-dl/commit/165841a5b15767f78dee8e551855cbc1d77a84a7, use the latest development version.

**Comment by mfechner** [comment]
Thanks a lot. I there a manual on how to build the udemy-dl.exe based on master branch?
