### ISSUE TITLE
[QUESTION] Issue while downloading videos of machinelearning course

### ISSUE THREAD

**Issue by alokjadhav** [nishad/udemy-dl#208]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

I am trying to download the **machinelearning** lecture. The downloader doesn't download any videos but it downloads other contents. I debug through the program and found out that in parse_video function, json_source doesn't contain the url of the video as shown in the attached image.  because of missing URL I keep getting error message

>  'Skipped. Expected quality not found!' 

for all videos. 

![udemy](https://cloud.githubusercontent.com/assets/9636137/25061319/4fa07108-21e6-11e7-95ca-c356be8b7b15.png)

Is this some new kind of course content that we are missing here? How can we fix this?

**Comment by alokjadhav** [comment]
I realize that this is same issue as posted yesterday [https://github.com/nishad/udemy-dl/issues/207](url)

**Comment by smeggingsmegger** [comment]
I have a potential fix for this here: https://github.com/nishad/udemy-dl/pull/209

All my courses are able to download now.

**Comment by alokjadhav** [comment]
thanks. it's working great.
