### ISSUE TITLE
choosing path and name of saved links

### ISSUE THREAD

**Issue by warkoy** [nishad/udemy-dl#21]
Hi nishad,

thanks so much for your effort. can you please make ability to choose path for saved links and also can chose name for saved links . this cmd -o work just for download video not for saved links.
i will very thankful

**Comment by mukhlesur-millon** [comment]
it will be added soon...

**Comment by mukhlesur-millon** [comment]
added here
``python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/patch-5``
usage: ``python -m udemy_dl -S C:/udemy-dl/links1.txt https://www.udemy.com/****``

**Comment by warkoy** [comment]
hi mukhlesur-millon

thank you very much Work like a charm :) thats what i need exactly
