### ISSUE TITLE
[QUESTION] ERROR-61 in downloading course

### ISSUE THREAD

**Issue by iamsmith41** [nishad/udemy-dl#218]
Version : udemy-dl 0.2.1
Using Ubuntu 17.04 x64 desktop version.

In raising this issue, I confirm the following (please check boxes, eg [X]):

[x ] I have read and understood the contributors guide.
[x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
[x ] I have checked that the issue I'm posting isn't already reported.
[x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in closed issues and in opened issues
[x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
My familiarity with the project is as follows (check one, eg [X]):

[ ] I have never used the project.
[x ] I have used the project briefly.
[ ] I have used the project extensively, but have not contributed previously.
[ ] I am an active contributor to the project.
[ ] If the project maintainer has any additional requirements, they will be listed here.

No additional requirements.

---

```
[INFO-944] Downloading to: /home/jack/Desktop
[INFO-133] Trying to log in ...
[INFO-162] Login success.
[INFO-194] Found course id: 112450
[INFO-206] Found course title: Course_Title
[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ad/.local/lib/python2.7/site-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/home/ad/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/home/ad/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 763, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/home/ad/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 409, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: u'results'

```

I didn't get this :  KeyError: u'results'
Why is this error coming for many courses. Can you please explain the cause and fix?

Thanks in advance.

**Comment by mxhryvo** [comment]
I have the same issue. Its not for all courses but for some.

**Comment by DEKHTIARJonathan** [comment]
I have the same issue wit this course: https://www.udemy.com/spark-and-python-for-big-data-with-pyspark/

**Comment by iamsmith41** [comment]
Hi,
Can anyone assist?
Thanks.

**Comment by iamsmith41** [comment]
Hi,
If anyone can help?

**Comment by yolao** [comment]
If anyone can help?

**Comment by mxhryvo** [comment]
Yeah this is really becoming a problem with udemy-dl. I can't download 3 courses without having one that gets this error.

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
