### ISSUE TITLE
Cannot download lecture

### ISSUE THREAD

**Issue by HumbertoIrena** [nishad/udemy-dl#22]
Hello guys,
When i ry to download the videos i get this message along with the name of the video

Example:
Cannot download lecture "Creating Mobile Apps With HTML5"
Cannot download lecture "Introducing jQuery Mobile"

Any idea why?
Thanks!

**Comment by mukhlesur-millon** [comment]
course link?

**Comment by Prakash26790** [comment]
Hi,
I also could not download the course videos.... Getting same error in both Windows and Ubuntu platforms.

Error got from Windows:
------------------------------
Downloading to: C:\Users\Prakash\Downloads\udemy-dl-win-2.0.1\udemy-dl-win\aws-c
ertified-sysops-administrator-associate

Cannot download lecture "Introduction to the AWS SysOps Administrator - Associat
e"
Cannot download lecture "Questions? Check out our discussion forums!"
..................................

Could you help me to download the videos by fixing the issues?
Else/Or if anything I'm doing wrong?

Course is : https://www.udemy.com/aws-certified-sysops-administrator-associate

**Comment by nishad** [comment]
Have you purchased the course and enrolled ?

**Comment by Prakash26790** [comment]
No, I did not purchased that....
Need to purchase to download?

**Comment by nishad** [comment]
This tool is not intended to infringe any copyrights of udemy. As the project's description , this will only help to get videos for personal offline use. Mainly due to bandwidth limitations of users from many developing countries. Please pay for the courses and respect udemy's business model.
