### ISSUE TITLE
[QUESTION] Getting error on quality not found

### ISSUE THREAD

**Issue by vanatomas** [nishad/udemy-dl#224]
Version : **udemy-dl 0.2.2-alpha**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [X] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
By using udemy-dl -u  username -p password http://

Getting course data: 0.90% [--------------------] [CRITICAL-268] Skipped. Expected quality not found!

I do not specify quality in command, what can be the issue

**Comment by jkgatt** [comment]
Check this out:[Issue 216](https://github.com/nishad/udemy-dl/issues/216)

**Comment by vanatomas** [comment]
@jkgatt thank you, had to reinstall v 0.2.2a1, works now.
