### ISSUE TITLE
'ascii' codec can't encode character u'\u2019'

### ISSUE THREAD

**Issue by vista980622** [nishad/udemy-dl#23]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 16: ordinal not in range(128)

![screen shot 2016-01-16 at 11 12 18](https://cloud.githubusercontent.com/assets/6680542/12370182/4c35014c-bc42-11e5-8f72-59147f30dca7.png)

![screen shot 2016-01-16 at 11 12 49](https://cloud.githubusercontent.com/assets/6680542/12370172/28e87fe8-bc42-11e5-8f60-a15d2587e782.png)

=======
Possible fix:
http://stackoverflow.com/questions/3224268/python-unicode-encode-error

**Comment by mukhlesur-millon** [comment]
it was fixed. upgrade it.
Error with some character like … #20

**Comment by mukhlesur-millon** [comment]
it was fixed here.
``python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/patch-5``

**Comment by nishad** [comment]
Hopefully https://github.com/nishad/udemy-dl/commit/0715b5c3b3d53d3702714d8567097eb054e3c204, is a fix for your issue. This is already in the development repository.

Usually, the fixes will reflect in PyPI only after a versioned release, You can see the instructions to install from the development repository here. 

https://github.com/nishad/udemy-dl/wiki/Installing-development-version
