### ISSUE TITLE
[QUESTION] - Cannot get it to work anymore

### ISSUE THREAD

**Issue by jcrawford** [nishad/udemy-dl#234]
I have tried to reinstall this using sudo pip install udemy-dl and it appears to work, says it installs but i cannot execute udemy-dl as the command is not found?

```sudo pip install udemy-dl
..........
Installing collected packages: udemy-dl  
  Running setup.py install for udemy-dl ... done  
Successfully installed udemy-dl-0.2.1```

```udemy-dl
zsh: command not found: udemy-dl```

```which udemy-dl
udemy-dl not found```

**Comment by nishad** [comment]
If binary is missing from path, you can try to execute it as a python module.

```
python -m udemy_dl https://www.udemy.com/COURSE_NAME
```

**Comment by jcrawford** [comment]
That works but why was the binary not installed?
