### ISSUE TITLE
Can not encode u'\u201c' aka "

### ISSUE THREAD

**Issue by Peppershaker** [nishad/udemy-dl#24]
can't seem to fix this myself

thanks in advance! great script

**Comment by mukhlesur-millon** [comment]
did you upgrade ? it was fixed at
Error with some character like … #20

**Comment by mukhlesur-millon** [comment]
it was fixed here.
``python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/patch-5``

**Comment by Peppershaker** [comment]
Yeah I ran the update. Still returns error

**Comment by mukhlesur-millon** [comment]
did you upgrade with it
python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/patch-5

**Comment by Peppershaker** [comment]
just tried again with posted upgrade. still returns error

Traceback (most recent call last):
  File "/Users/~~/anaconda/bin/udemy-dl", line 5, in <module>
    main()
  File "/Users/~~/anaconda/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 327, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, save_links, save_links_path)
  File "/Users/~~/anaconda/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 255, in udemy_dl
    filename = '{0:03d} {1!s}.mp4'.format(video['lecture_number'], video['lecture'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 29: ordinal not in range(128)

**Comment by Peppershaker** [comment]
MacBook-Pro-2:~ VVV$ python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/patch-5
Collecting https://github.com/mukhlesur-millon/udemy-dl/zipball/patch-5
  Downloading https://github.com/mukhlesur-millon/udemy-dl/zipball/patch-5
     | 12kB 468kB/s
Requirement already up-to-date: requests in ./anaconda/lib/python2.7/site-packages (from udemy-dl==0.2.0)
Requirement already up-to-date: wget in ./anaconda/lib/python2.7/site-packages (from udemy-dl==0.2.0)
Building wheels for collected packages: udemy-dl
  Running setup.py bdist_wheel for udemy-dl
  Stored in directory: /Users/VVV/Library/Caches/pip/wheels/04/f7/f8/57cec911bd6771253f968d81732feeea47e1ca277d0628e208
Successfully built udemy-dl
Installing collected packages: udemy-dl
  Found existing installation: udemy-dl 0.2.0
    Uninstalling udemy-dl-0.2.0:
      Successfully uninstalled udemy-dl-0.2.0
Successfully installed udemy-dl-0.2.0

**Comment by Peppershaker** [comment]
the script needs to use " for both file name as well as folder name

**Comment by mukhlesur-millon** [comment]
``
# -*- coding: utf-8 -*-
filename = 'Model, View, Whatever…'
filename = '{0:03d} {1!s}.mp4'.format(65, filename)
print(filename)
``
please run this..

**Comment by Peppershaker** [comment]
sorry do i run the entirety of 

-- coding: utf-8 --
filename = 'Model, View, Whatever…'
filename = '{0:03d} {1!s}.mp4'.format(65, filename)
print(filename)

or just -- coding: utf-8

**Comment by Peppershaker** [comment]
udemy-dl https://www.udemy.com/ultimate-guide-to-ux -- coding: utf-8

does not execute :( sorry pretty noob

**Comment by Peppershaker** [comment]
"https://gist.github.com/mukhlesur-millon/42812f6c691bc4e23012"

no such file or directory

**Comment by mukhlesur-millon** [comment]
save these code in file name `t.py`
and run
``python t.py``

**Comment by Peppershaker** [comment]
printed 065 Model, View, Whatever….mp4

**Comment by mukhlesur-millon** [comment]
this works and udemy-dl should work.
i don't know why udemy-dl doesn't work.
i will try my best to solve this.

**Comment by Peppershaker** [comment]
hey man, do you mind having another look, seems like the only time it throws an error is when there's ' and " involved

thanks a ton!

**Comment by Peppershaker** [comment]
also, windows version works fine

**Comment by nishad** [comment]
Hopefully https://github.com/nishad/udemy-dl/commit/0715b5c3b3d53d3702714d8567097eb054e3c204, is a fix for your issue. This is already in the development repository.

Usually, the fixes will reflect in PyPI only after a versioned release, You can see the instructions to install from the development repository here. 

https://github.com/nishad/udemy-dl/wiki/Installing-development-version
