### ISSUE TITLE
Raspberrypi - [CRITICAL-238] Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by F1shst4le** [nishad/udemy-dl#246]
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

Hello, i used the udemy-dl on my windows machine but now i wanted to use it on my raspberrypi running debian jessie .. 

The main problem when trying to download is:
[INFO-107] Trying to log in ...
[INFO-137] Login success.
[INFO-169] Found course id: 148524
Getting course data: 7.69% [==------------------] [CRITICAL-238] Skipped. Expected quality not found!

i already tried : 
sudo apt-get install python-lxml
sudo pip install -U git+https://github.com/smeggingsmegger/udemy-dl.git@master

but i am stuck at this: 
(especially 

Failed building wheel for lxml
Failed building wheel for Pillow

pi@raspberrypi:~/Downloads $ sudo pip install -U git+https://github.com/smeggingsmegger/udemy-dl.git@master
Collecting git+https://github.com/smeggingsmegger/udemy-dl.git@master
  Cloning https://github.com/smeggingsmegger/udemy-dl.git (to master) to /tmp/pip-xSrOei-build
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from udemy-dl==0.2.3-alpha)
Requirement already up-to-date: unicode-slugify in /usr/local/lib/python2.7/dist-packages (from udemy-dl==0.2.3-alpha)
Requirement already up-to-date: colorlog in /usr/local/lib/python2.7/dist-packages (from udemy-dl==0.2.3-alpha)
Requirement already up-to-date: future in /usr/local/lib/python2.7/dist-packages (from udemy-dl==0.2.3-alpha)
Collecting python-pptx (from udemy-dl==0.2.3-alpha)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->udemy-dl==0.2.3-alpha)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->udemy-dl==0.2.3-alpha)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->udemy-dl==0.2.3-alpha)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->udemy-dl==0.2.3-alpha)
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from unicode-slugify->udemy-dl==0.2.3-alpha)
Requirement already up-to-date: unidecode in /usr/local/lib/python2.7/dist-packages (from unicode-slugify->udemy-dl==0.2.3-alpha)
Requirement already up-to-date: XlsxWriter>=0.5.7 in /usr/local/lib/python2.7/dist-packages (from python-pptx->udemy-dl==0.2.3-alpha)
Collecting lxml>=3.1.0 (from python-pptx->udemy-dl==0.2.3-alpha)
  Using cached lxml-3.8.0.tar.gz
Collecting Pillow>=2.6.1 (from python-pptx->udemy-dl==0.2.3-alpha)
  Using cached Pillow-4.2.1.tar.gz
Collecting olefile (from Pillow>=2.6.1->python-pptx->udemy-dl==0.2.3-alpha)
Building wheels for collected packages: lxml, Pillow
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8RTNGi/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpJq7aXepip-wheel- --python-tag cp27:
  Building lxml version 3.8.0.
  Building without Cython.
  ERROR: /bin/sh: 1: xslt-config: not found
  
  ** make sure the development packages of libxml2 and libxslt are installed **
  
  Using build configuration of libxslt
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/sax.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/__init__.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/builder.py -> build/lib.linux-armv7l-2.7/lxml
  creating build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-2.7/lxml/includes
  creating build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-armv7l-2.7/lxml/html
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-2.7/lxml
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-2.7/lxml/includes
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-armv7l-2.7
  creating build/temp.linux-armv7l-2.7/src
  creating build/temp.linux-armv7l-2.7/src/lxml
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-armv7l-2.7/src/lxml/lxml.etree.o -w
  src/lxml/lxml.etree.c:84:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
   #include "Python.h"
                      ^
  compilation terminated.
  Compile failed: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  creating tmp
  cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitLl9HTi.c -o tmp/xmlXPathInitLl9HTi.o
  /tmp/xmlXPathInitLl9HTi.c:1:26: fatal error: libxml/xpath.h: Datei oder Verzeichnis nicht gefunden
   #include "libxml/xpath.h"
                            ^
  compilation terminated.
  *********************************************************************************
  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  *********************************************************************************
  error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py clean for lxml
  Running setup.py bdist_wheel for Pillow ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8RTNGi/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpn1MFwzpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/PIL
  copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/version.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL
  running egg_info
  writing requirements to Pillow.egg-info/requires.txt
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-8RTNGi/Pillow/setup.py", line 788, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  
  ----------------------------------------
  Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build lxml Pillow
Installing collected packages: lxml, olefile, Pillow, python-pptx, udemy-dl
  Found existing installation: lxml 3.4.0
    Uninstalling lxml-3.4.0:
      Successfully uninstalled lxml-3.4.0
  Running setup.py install for lxml ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8RTNGi/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7lztzN-record/install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.8.0.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/cssselect.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/sax.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/__init__.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/builder.py -> build/lib.linux-armv7l-2.7/lxml
    creating build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-2.7/lxml/includes
    creating build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-2.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.linux-armv7l-2.7/lxml/html
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-2.7/lxml/isoschematron
    copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-2.7/lxml
    copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-2.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-2.7/lxml/includes
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
    creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.linux-armv7l-2.7
    creating build/temp.linux-armv7l-2.7/src
    creating build/temp.linux-armv7l-2.7/src/lxml
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-armv7l-2.7/src/lxml/lxml.etree.o -w
    src/lxml/lxml.etree.c:84:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
     #include "Python.h"
                        ^
    compilation terminated.
    Compile failed: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitf5mU9e.c -o tmp/xmlXPathInitf5mU9e.o
    /tmp/xmlXPathInitf5mU9e.c:1:26: fatal error: libxml/xpath.h: Datei oder Verzeichnis nicht gefunden
     #include "libxml/xpath.h"
                              ^
    compilation terminated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    *********************************************************************************
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of lxml
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8RTNGi/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7lztzN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-8RTNGi/lxml/
pi@raspberrypi:~/Downloads $

**Comment by DragosPaul95** [comment]
Same issue here on macOS 10.12.6

**Comment by tomaszcysewski** [comment]
thx I came across the same issue but on linux 17.04. fixed by reinstalling

**Comment by F1shst4le** [comment]
Thanks to DragosPaul95 ... 
now it works !! 
thank you so much
