### ISSUE TITLE
I couldn't download the videos

### ISSUE THREAD

**Issue by karesh** [nishad/udemy-dl#257]
I have paid for some videos and I could't download the videos.

`Getting course data: 99.38% [====================] [CRITICAL-238] Skipped. Expected quality not found!
`
then it is downloading only the html files.

I ran a command. 

`udemy-dl https://www.udemy.com/course-name/..
`

**Comment by PedroFumero** [comment]
Same here.

**Comment by raul3k** [comment]
Yes, same here.

**Comment by NeuroWinter** [comment]
Same here

**Comment by Arkist5** [comment]
Same here.

**Comment by raul3k** [comment]
Hello.
For who has the same error as me or the others as described in this thread, use the following command to download the last version of the software (that worked for me and there is some others commands better than that, just look in the issues):

`sudo pip install udemy-dl==0.2.2-alpha.2`

**Comment by arsenico13** [comment]
Thank you @raul3k, that solved the problem for me!

**Comment by karesh** [comment]
Yes udemy-dl==0.2.2-alpha.2 worked. Thanks.
