### ISSUE TITLE
the .exe file closes within a sec after running

### ISSUE THREAD

**Issue by sarthak-pandit** [nishad/udemy-dl#27]
please help with it
as soon as i run udemy-dl.exe  the command screen just opens and closes.

**Comment by nishad** [comment]
This distribution doesn't have any `.exe` files.

**Comment by mukhlesur-millon** [comment]
it seems, you are using ``https://github.com/nishad/udemy-dl-windows/tree/master/dist`` this one.
if you want to use it, you have to open it with cmd. you cant open it with just double clicking on it.
