### ISSUE TITLE
Failed to get course ID

### ISSUE THREAD

**Issue by harshamv** [nishad/udemy-dl#3]
i upgraded to the latest script but still i am getting the following error.

```
udemy-dl -u hm######@gmail.com -p h$$$$$$$$$ https://www.udemy.com/hacking-airbnb-how-i-make-60000-a-year-from-my-spare-room
```

Get the follwoing error

```
Downloading to: /home/udemy/hacking-airbnb-how-i-make-60000-a-year-from-my-spare-room

Failed to get course ID

```

Looks like Udemy has changed the URL or something.

**Comment by nishad** [comment]
Which version of `udemy-dl` you are using ?
Could you post output of 
`udemy-dl -v` 
--

**Comment by harshamv** [comment]
this is weird 

```
/home/udemy# udemy-dl -v
usage: udemy-dl [-h] [-u USERNAME] [-p PASSWORD]
                [--lecture-start LECTURE_START] [--lecture-end LECTURE_END]
                [-o OUTPUT_DIR]
                link
udemy-dl: error: too few arguments
```

**Comment by nishad** [comment]
Seems like you are using an older version of the script. Uninstall it with pip and follow the instructions from this issue thread https://github.com/nishad/udemy-dl/issues/1

**Comment by harshamv** [comment]
yeah. i just got it working. looks like i had 0.17v

Looks like following this it doesnt work and is installing the older ver.
https://pypi.python.org/pypi/udemy-dl

**Comment by fahadahmedtyler** [comment]
Hi - I am trying to download it on windows and using the latest version 2.0.1 but gettng this error? What could have gone wrong?

**Comment by mukhlesur-millon** [comment]
@fahadahmedtyler `python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master` this should fix your problem. please  let me know what is the result.

**Comment by cycomarcooo** [comment]
Hi, I was using 0.2 version and I got the same error : Failed to get course ID.
@mukhlesur-millon : it works with your version.

**Comment by yomiyusuf** [comment]
@mukhlesur-millon i have the same problem but i can't get your line of code to work. it says `"python" is not recognised as an internal or external command`

**Comment by mukhlesur-millon** [comment]
@yomiyusuf  see here, how to setup python http://docs.python-guide.org/en/latest/starting/install/win/ and http://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7

or it is better to use https://github.com/nishad/udemy-dl-windows

**Comment by yasserdhia** [comment]
@mukhlesur-millon Im try this comand : python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master
but this error : # Failed to get course ID  is still appear . Please Answer Me To Fix That !!!

**Comment by yomiyusuf** [comment]
@MRMillon thanks for your reply.
I have used the https://github.com/nishad/udemy-dl-windows repo annd i still get the same Failed to get course ID.

**Comment by mahdi87gh** [comment]
TypeError: string indices must be integers

I get this error in latest version

**Comment by nishad** [comment]
@mahdi87gh  This is a closed thread and it is related a different issue, You can comment in any opened report, similar to yours or create a new issue.

**Comment by nehemiekoffi** [comment]
What is the resolution of this thread? I'm using the recent version 2.01 and still get the same error : Failed to get course ID

**Comment by anschauhanex** [comment]
me too
