### ISSUE TITLE
My Internet speed is 10Mbps but it is downloading with a speed of 12Kbps

### ISSUE THREAD

**Issue by ndixit01** [nishad/udemy-dl#30]
The download speed is so low that  to download the introduction file it takes a total of 25 minutes however, everything else is downloading fine except the tutorial. I have checked my internet connection  and its working fine. I think that it is an issue with the downloader. Do you think that by some way i can download using IDM
Also when choose the save links option it says that the links have been saved to the directory but there are no files in the directory.

**Comment by mukhlesur-millon** [comment]
if you have problem with speed then install curl...
to save links to your desire directory use  this...
``python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/patch-5``
usage: ``python -m udemy_dl -S C:/udemy-dl/links1.txt https://www.udemy.com/****``
saved links will be found at ``C:\udemy-dl\``

--save-link will save the file where you run udemy-dl... if don't found it then it may be here ``C:\Python\Lib\site-packages\udemy_dl``

**Comment by ndixit01** [comment]
Now, I have installed curl but it is still giving a speed of 50Kbps while my internet speed is 10Mbps. Any advice to increase the speed further. The downloading speed should be 900 KBps

**Comment by mukhlesur-millon** [comment]
then use idm...

**Comment by mukhlesur-millon** [comment]
download with idm was added..
- install: ``python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master``
- usage:``python -m udemy_dl -u USERNAME -p PASSWORD -d idm https://www.udemy.com/******``

This will add files to ``Main download queue of idm``
- Start download: ``idm > scheduler > Main download queue > Files in the queue [download 1 files at the same time] > Start now > close``
