### ISSUE TITLE
[PROPOSAL] Download files attached to lesson

### ISSUE THREAD

**Issue by sun2rise** [nishad/udemy-dl#32]
Hi, thank you for your work.
Would it be possible to make available for download files like txt, pdf, slides or whatever is attached to a lesson?
This would make the course backup really complete for a good personal library.

Thank you again

**Comment by mukhlesur-millon** [comment]
this will be added.. :+1:

**Comment by ChristianAE** [comment]
+1

**Comment by vanatomas** [comment]
any updates on this one?

**Comment by mukhlesur-millon** [comment]
i can do this but  it will not save the attached file on that chapter's folder.  i can save them on a  new folder.

**Comment by sun2rise** [comment]
My personal feedback is that is ok, as long as the file has a meaningful name like <lesson number> - <filename>. i think it would be enough to pair the document with the right lesson.

Thank you for the mod.!

**Comment by mukhlesur-millon** [comment]
_did it work? i forgot to import wget._

**Comment by vanatomas** [comment]
Getting this error 
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 6, in <module>
    from udemy_dl.udemy_dl import main
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 337
    def uprint(*objects, sep=' ', end='\n', file=sys.stdout):
                           ^
SyntaxError: invalid syntax

**Comment by mukhlesur-millon** [comment]
use python3.

**Comment by vanatomas** [comment]
you mean to upgrade to Python 3 or there is a way to do so without upgrading?

**Comment by mukhlesur-millon** [comment]
ubuntu has both python2 and python3.
what is your os?

**Comment by mukhlesur-millon** [comment]
as it supports all known asset types, `uprint` is not necessary.

**Comment by vanatomas** [comment]
I have mac, just did brew install python3, but when try to run udemy, seems like it is still trying to use python 2.7. Any idea on fixing such?

**Comment by mukhlesur-millon** [comment]
i have no idea about mac
if this works ``python3 -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master``

then use it 
``python3 -m udemy_dl``

**Comment by vanatomas** [comment]
ok that works, thx. however, checking on d/l, I do not see anything beside videos being downloaded. Will those downloaded at the end or should be along with videos?

**Comment by mukhlesur-millon** [comment]
i think you haven't notice saving attached item at ... while Getting the video links

**Comment by mukhlesur-millon** [comment]
i have remove uprint , it should work on python2

**Comment by vanatomas** [comment]
nvm, looks good, got pdfs, ty

**Comment by vanatomas** [comment]
btw is there a way to remove b that appends to the folder or file title?

**Comment by mukhlesur-millon** [comment]
python2 does not add `b`.

**Comment by AnuragChauhan07** [comment]
Thanks In Advance for this ENHANCEMENT .

**Comment by jcrawford** [comment]
I just used 0.2.1-beta and I am not seeing any of the attached files being pulled down, is python 3 a requirement for downloading the attached files?  I am running 2.7.11 on my mac but I would love the ability to have the course files downloaded as well. 

It seems to be using the internal downloader and it downloads the videos and the articles (html) but does not seem to even acknowledge the attached files.  Could this be something that needs to be updated to work again since Udemy changed the UI?

**Comment by mukhlesur-millon** [comment]
@jcrawford udemy-dl currently doesn't support that. it will be added after solving some issues. it works same in python 2 and 3.

**Comment by jcrawford** [comment]
@mukhlesur-millon Ah perfect I thought this was saying that it was already in place :)  I look forward to that feature it will make things much easier.

**Comment by mukhlesur-millon** [comment]
Downloading files attached to lecture has added with better support. upgrade it from [here](https://github.com/nishad/udemy-dl/wiki/Installing-development-version)

**Comment by jcrawford** [comment]
This is awesome, thank you very much :)

**Comment by nishad** [comment]
Fixed with v0.2.1. Follow steps in https://github.com/nishad/udemy-dl/blob/master/README.md#update to update.
