### ISSUE TITLE
CANT SUCCESS

### ISSUE THREAD

**Issue by badao93** [nishad/udemy-dl#34]
i try many time but cant success full.always take that "can not down load the video"????

**Comment by badao93** [comment]
![ngocbu](https://cloud.githubusercontent.com/assets/15267228/12756864/371b394c-ca08-11e5-8282-00d0c9381c6e.PNG)

**Comment by nishad** [comment]
Are you sure, you have **purchased and enrolled** in this course?

**Comment by Lawen78** [comment]
you need to purchase the course (if it's not free) or you get this messages.
