### ISSUE TITLE
Issue - UnicodeEncodeError

### ISSUE THREAD

**Issue by SlayerZero** [nishad/udemy-dl#35]
Before anything great work in the new update of the tool.

Now, this is tha issue.

is from the udemy url: https://www.udemy.com/cisco-ccna-routing-and-switching-200-120/

![image](https://cloud.githubusercontent.com/assets/3946897/12768615/773505da-c9d6-11e5-9dde-d8b809818d1c.png)

Thanks for all, and best regards

**Comment by nishad** [comment]
A temporary fix is

```
python -m pip install --upgrade https://github.com/nishad/udemy-dl/archive/0715b5c.zip
```
