### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 20: 

### ISSUE THREAD

**Issue by Lawen78** [nishad/udemy-dl#36]
Hi,

I got this error when I try to download a course with full access, because in the title there's some words like 'à' or 'é'.

**Comment by mukhlesur-millon** [comment]
upgrade it
``python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master``

**Comment by Lawen78** [comment]
After your update I got this error:

Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 6, in <module>
    from udemy_dl.udemy_dl import main
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 289
    def uprint(*objects, sep=' ', end='\n', file=sys.stdout):
                           ^
SyntaxError: invalid syntax

, and I need to uninstall and reinstall with: python -m pip install --upgrade udemy-dl.

I've also tried to uninstall, then launch your command but I got the same error.

**Comment by nishad** [comment]
Current development version is not good enough for python 2, will resolve that in next release. However a temporary fix is here https://github.com/nishad/udemy-dl/issues/35#issuecomment-178937590
