### ISSUE TITLE
Storage system

### ISSUE THREAD

**Issue by Erre** [nishad/udemy-dl#38]
Hi there. 

First of all, many compliments for the script.

I am trying to setup a similar website/webstorage for my dad's little business, which would be very similar to udemy. I was wondering if you know what kind of system udemy uses (something like NAS), since you coded the script.

Sorry if I am posting here, but I couldn't find your personal email anywhere.

**Comment by mukhlesur-millon** [comment]
[John Purcell](https://www.udemy.com/user/johnpurcell/) has a similar website name [Cave of Programming](http://courses.caveofprogramming.com/courses), contact with him, he might help you. and close this one.
