### ISSUE TITLE
ASCII codec can't encode character

### ISSUE THREAD

**Issue by SaFi2266** [nishad/udemy-dl#39]
Hi,
Thanks a lots for great work.
I encountered the error below when downloading lectures with name title 
"Domain–Structure, Elements, Dynamic UI Behaviors with ATTRS and ONCHANGE: Part 1".

```
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 289, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, save_links)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 219, in udemy_dl
    filename = '{0:03d} {1!s}.mp4'.format(video['lecture_number'], video['lecture'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 6: ordinal not in range(128)
```
I guess that's you don't include this line below in the script
```
from __future__ import unicode_literals
```
so please confirm that or correct me if i am wrong

TIA
SaFi

**Comment by SaFi2266** [comment]
Hello again,

After reviewing your script code I see you include the line 
```
from __future__ import unicode_literals
```
will you please help me to override this

**Comment by mukhlesur-millon** [comment]
Issue - UnicodeEncodeError #35
`python -m pip install --upgrade https://github.com/nishad/udemy-dl/archive/0715b5c.zip`

**Comment by nishad** [comment]
Thanks @mukhlesur-millon.

**Comment by nishad** [comment]
Unicode file-names are kind of an issue. I'm aware of it specially the difference between Python2 and 3. However the udemy purchase is life long, so you ou can use `--lecture-start` and `--lecture-end` to skip this issue for a time-being.
