### ISSUE TITLE
Do not start download

### ISSUE THREAD

**Issue by scarnago** [nishad/udemy-dl#4]
I'm using latest version udemy-dl 0.1.8 in Xubuntu 15.04, when I execute **"udemy-dl url_course"** in Linux Terminal ask for username and password and after I just receive a bunch of HTML and CSS relates to login page in Udemy and **udemy-dl** stops

**Comment by nishad** [comment]
How long you are getting this issue ? Are you sure you are using valid username and password?

**Comment by nishad** [comment]
It seems like this tool is not working for you, please stop using this tool and try to find any other alternatives.
