### ISSUE TITLE
[PROPOSAL] Numbering not according to lecture number when course contains articels

### ISSUE THREAD

**Issue by ChristianAE** [nishad/udemy-dl#42]
If a course contains articles/quiz the numbering of the downloaded videos is not the same as on the website.

i.e. if the website contains the following lectures:
Lecture 1: Introduction (Video)
Lecture 2: Source code (Article)
Lecture 3: Case Study (Video)

The download folder will contain the following files:
001 Introduction.mp4
002 Case Study.mp4 (it should be 003 Case Study.mp4)

**Comment by mukhlesur-millon** [comment]
now it  support 'Video', 'E-Book', 'VideoMashup', 'Audio', 'Presentation', 'Article'
``python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master``

**Comment by nishad** [comment]
It is fixed with https://github.com/nishad/udemy-dl/commit/b493903fb5400956276f487df1b2731151d5b9f6, you can try again with the latest development version.

**Comment by ChristianAE** [comment]
Places now an .html file for non video content, keeping the numbering intact.
