### ISSUE TITLE
[BUG] Error: Couldn't fetch token !

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [nishad/udemy-dl#43]

**Comment by mukhlesur-millon** [comment]
it was fixed.

**Comment by Vulgaris-Viridis** [comment]
I tried to upgrade it before I've posted the bug (though i didn't know it was fixed in the following version), but I received following errors:

curl: (22) The requested URL returned error: 404 Not Found
ERROR : Failed to download latest udemy-dl.exe

curl: (22) The requested URL returned error: 404 Not Found
ERROR : Failed to download latest curl.exe

curl: (22) The requested URL returned error: 404 Not Found
ERROR : Failed to download latest update.cmd

**Comment by mukhlesur-millon** [comment]
you are using another version of udemy-dl. for further help go to `https://github.com/nishad/udemy-dl-windows`

**Comment by Vulgaris-Viridis** [comment]
Yes, my bad I accidentally opened the issue for this one ... Should I close this one and post the mentioned bug for the other one then?

**Comment by mukhlesur-millon** [comment]
yes... if you had problem with udemy-dl.exe,  then you should go to https://github.com/nishad/udemy-dl-windows

**Comment by Vulgaris-Viridis** [comment]
Sure thing..Thanks..
