### ISSUE TITLE
[PROPOSAL] lower video quality

### ISSUE THREAD

**Issue by adeemkazi** [nishad/udemy-dl#44]
Can you please make arrangemnets for downloading a lower video quality.
my internet is too slow so downloading 1080p videos take ages

**Comment by Gemsmith** [comment]
Hey Nishad any update on adding the feature of setting Video Quality?
If you're still working on it may I make a suggestion. 
It would be so simple if user could just input a set priority to be used always. Ex. 3 2 4 1. Where the numbers correspond to 1(240p) to 4(1080p).
Ex. User wants readable quality but not too high either, so he saves 3 2 4 1 so if medium is not there high quality is downloaded.
