### ISSUE TITLE
[BUG] UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 3: 

### ISSUE THREAD

**Issue by badrsh** [nishad/udemy-dl#49]
I Have this error when i try to download the videos 

```
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 289,                   in main
    udemy_dl(username, password, link, lecture_start, lecture_end, output_dir, s                  ave_links)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 219,                   in udemy_dl
    filename = '{0:03d} {1!s}.mp4'.format(video['lecture_number'], video['lectur                  e'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 3:                   ordinal not in range(128)

```

what is the problem please

**Comment by nishad** [comment]
It is fixed with https://github.com/nishad/udemy-dl/commit/988a6d4aae68cc5e8eb55d40a4081a29a377dd7c, you can try again with the latest development version.

**Comment by ar1n4mu** [comment]
Thanks a lot for this tool. 
Previous version worked fine for two courses, but in the third course I got the error "UnicodeEncodeError", as mentioned by badrsh above. Therefore, I have installed the development version, but now I'm getting these errors on all the courses:


Downloading to: /path

Trying to log in ... and we're done.
Getting course data: 3.57% [.                   ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 5.36% [.                   ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 8.93% [..                  ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 10.71% [..                  ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 12.50% [...                 ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 14.29% [...                 ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 16.07% [...                 ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 17.86% [....                ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 19.64% [....                ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 23.21% [.....               ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 25.00% [.....               ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 26.79% [.....               ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 28.57% [......              ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 32.14% [......              ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 33.93% [.......             ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 37.50% [........            ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 39.29% [........            ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 41.07% [........            ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 42.86% [.........           ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 44.64% [.........           ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 46.43% [.........           ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 50.00% [..........          ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 51.79% [..........          ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 53.57% [...........         ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 55.36% [...........         ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 57.14% [...........         ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 58.93% [............        ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 62.50% [.............       ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 64.29% [.............       ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 66.07% [.............       ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 67.86% [..............      ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 69.64% [..............      ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 73.21% [...............     ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 75.00% [...............     ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 76.79% [...............     ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 78.57% [................    ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 80.36% [................    ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 82.14% [................    ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 83.93% [.................   ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 85.71% [.................   ] Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 100.00% [....................] Done
Cannot download lecture "XXX" as "'NoneType' object has no attribute '__getitem__'"
Downloading Ebook: 041 Six Sigma Yellow Belt Lecture Slides
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1960k  100 1960k    0     0   542k      0  0:00:03  0:00:03 --:--:--  542k

Now, all videos are being downloaded partially. 

I use Debian 8, so I had to install udemy_dl manually.
