### ISSUE TITLE
[PROPOSAL] While downloading mark files as temporary

### ISSUE THREAD

**Issue by ChristianAE** [nishad/udemy-dl#53]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

When a download gets interrupted it leaves behind a unfinished .mp4 file. This leads to the behavior that this lecture will be skipped when the download process is initiated again, leaving an incomplete video file.

I suggest to use a _.temp_ extension while the download is incomplete and only rename the file if the download was successful. This way on the next run the .temp file can just be discarded and the download for the lecture initiated again.

**Comment by nishad** [comment]
`curl` is the preferred downloader for `udemy-dl`, `curl` is used with `-C` as a default option. This will force `curl` to resume broken downloads, which is safe.

Proposed behavior is similar to `youtube-dl`. You can use `youtube-dl` as well to achieve this result.

```bash
youtube-dl https://www.udemy.com/......../learn/ -o '%(playlist_title)s/%(chapter_number)s-%(chapter)s/%(playlist_index)s-%(title)s.%(ext)s' -u your@email.here -p your_password_here
```

**Comment by ChristianAE** [comment]
I don't know what I did wrong the first two times but I was not able to reproduce it.

I can confirm now that a interrupted download just picks up where it's left of and the interrupted .mp4 will be complete in the end.

I apologies for the wrongly opened issue.
