### ISSUE TITLE
[PROPOSAL] - change mp4 download extension to given extension in link.

### ISSUE THREAD

**Issue by YoColdRain** [nishad/udemy-dl#54]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [X] I have read and understood the [contributors guide]().
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

This is an issue and also a Fix.

I've been taking a class at udemy and recently realized one of the file from my course wasn't downloaded, and had extension of xml.  After going through code, I realized download.py file only looks for extension of pdf and mp3, so instead of adding xml, I propose following.
Replace this code : 
```python
if '.pdf' in link:
    filename = filename.rstrip('mp4') + 'pdf'
elif '.mp3' in link:
    filename = filename.rstrip('mp4') + 'mp3'`
```

with this code: 
```python
delim = link.split('?')[0].rpartition('.')[2]
if delim in link:
    filename = filename.rstrip('mp4')+delim
```
this will look for any extension in the link and replace mp4 accordingly.  

I'd like to contribute more to this project and do not have good knowledge of PR/Forks etc... so pardon my ignorance and suggestion to improve my knowledge are welcome.

**Comment by nishad** [comment]
Thanks for pointing this out. Changes are made in https://github.com/nishad/udemy-dl/commit/6b6205d29f9733b12611975b86099044fc7ec1ba.

**Comment by mukhlesur-millon** [comment]
@nishad i haven't find a very beginner and very easy article on how to contribute in github, can i add it in wiki?

**Comment by nishad** [comment]
Thanks @mukhlesur-millon , please go ahead.

**Comment by alialpha123** [comment]
Nishad sir i have latest version of udemy-dl-win
it was working fine but suddenly now it gives error "failed to get course id"
please help :(

**Comment by mukhlesur-millon** [comment]
@alialpha123 it was fixed. you will get a update for [udemy-dl-win](https://github.com/nishad/udemy-dl-windows)

**Comment by alialpha123** [comment]
@mukhlesur-millon i have version 2.0.1 you will post new and latest version?

**Comment by mukhlesur-millon** [comment]
@YoColdRain this draft and quick version may help you
https://github.com/nishad/udemy-dl/wiki/Contributing-in-udemy-dl

**Comment by alialpha123** [comment]
@mukhlesur-millon udemy have been updated u can see while watching preview of any course so u and nishad sir will make new script?

**Comment by mukhlesur-millon** [comment]
no @alialpha123

**Comment by alialpha123** [comment]
so it means now we cant download courses for offline use and free?

**Comment by mukhlesur-millon** [comment]
you can download if have enrolled in a course free or paid. but udemy.com doesn't support downloading in preview mode. @alialpha123

**Comment by alialpha123** [comment]
before update when we click on start free preview of any paid course so udemy-dl-win downloadeds all lectures

**Comment by alialpha123** [comment]
before update when we click on start free preview of any paid course so udemy-dl-win downloadeds all lectures

**Comment by egadgetjnr** [comment]
Which is piracy, and illegal. 

The best option you have is to buy the course and then try it then. It will then work. :)
