### ISSUE TITLE
[BUG] --lecture-end does not work [not implemented?]

### ISSUE THREAD

**Issue by Cueball** [nishad/udemy-dl#55]
**[BUG]**

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**
- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---
It appears that the `--lecture-end` option is not implemented (correctly? or at all?)

A cursory inspection of `src/udemy_dl/udemy_dl.py` (`:509` - `:513`) shows a sanitary code check for `--lecture-start`, but no corresponding check for `--lecture-end`.

Hacking in a corresponding sanitary check for `--lecture-end` seems to have the desired effect on my system, but I get a '`global debug`' warning. At this point I lack the time and motivation to brush up on my Python to fix it any further (otherwise I would fix it and send a PR - sorry.)

FTR I'm running Python 2.7.11 on OS X 10.11.4ß via Homebrew; pip 8.1.0.

**Comment by nishad** [comment]
Fixed with https://github.com/nishad/udemy-dl/commit/5c3e1cbd098dc284384e6adb8bfb59569933692b. Thanks for pointing this out. 

:sake: 乾杯
