### ISSUE TITLE
[BUG] Failed to get course ID

### ISSUE THREAD

**Issue by pathankp** [nishad/udemy-dl#56]
it seems Udemy updated their site now there is no more timer in preview, kindly fix this issue as soon as possible.

**Comment by mukhlesur-millon** [comment]
Best option is you have to buy a course and this tool does'y support piracy.

**Comment by Thomas-Pelfrene** [comment]
I have a "Failed to get course ID" message.. How can I fix it ? Thanks in advance.

**Comment by mukhlesur-millon** [comment]
@Thomas-Pelfrene  upgrade it
`python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master`

**Comment by Thomas-Pelfrene** [comment]
Thanks, but even after upgrading, I always have the same error message "Failed to get course ID" :/

**Comment by mukhlesur-millon** [comment]
this may fix your problem
`python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master`

**Comment by dasilva19** [comment]
yeah same problem here, it doesn't work with the fix mukhlesur-millon, does it work for you?

**Comment by Thomas-Pelfrene** [comment]
thanks for return but it doesn't work.. :/

**Comment by Syed-Niotic** [comment]
The udemy update doesn't allow for pirating anymore, so guess we are out of luck :'( 
@mukhlesur-millon's version has the same issue. hopefully there is a fix soon :) but good work nonetheless :)

**Comment by nishad** [comment]
**`udemy-dl` is not intended to breach any udemy copyrights or it's business model. This tool is developed and maintained for legitimate users to keep an offline version of the course, mainly videos. This issue tracker will not tolerate or entertain any such illegal, or unethical activities.**

Soon there will be a public **`Hall of Shame`** list, where all users who violate this ethical cause will be listed, and all issues reported by them will be ignored.

**Comment by nishad** [comment]
@Thomas-Pelfrene, you can run `udemy-dl` with `--debug` option, and you can post the debug html, here or in https://gist.github.com/

**Comment by wick3rman** [comment]
I have managed to fix  this issue by changing the script to let the user manually enter the course ID. Getting the course ID isn't that hard, the downside is, it adds a new process that may be lengthy to some, but it isn't that bad.

![udemy script](https://cloud.githubusercontent.com/assets/17740696/13839198/453cbb24-ec2a-11e5-8c3b-ff42533e72fa.PNG)

To use the fix:
1. Copy the "udemy_dl.py" to C:\Users\%USERNAME%\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\udemy_dl\ and replace. 
**But please make a copy of the original file**
2. Run as usual in cmd "py -m udemy_dl" //With the proper arguments.

 File: 
[udemy_dl.zip](https://github.com/nishad/udemy-dl/files/177434/udemy_dl.zip)

To get the course ID : 
1. Open your browser in Private/incognito mode ( in case you are logged in Udemy ).
2. Paste the link of the course to your browser.
3. Go to more options, and copy the link address of "Bulk purchase"
![link](https://cloud.githubusercontent.com/assets/17740696/13839312/200ef636-ec2b-11e5-8812-3cc3ab9fd328.PNG)

4. Paste it to a Text editor, and you'll have a link like this : https://www.udemy.com/payment/buy-licenses-popup/?courseId=42xxxx
5. Copy the course ID and paste it when prompted in the console window.

6.The course will start downloading as usual.

Note: 
- I`m new to Github, so i don't know if I'm allowed to do this without permission from the original     author. If I'm not, then please I'm very very sorry.
- I hope @nishad will work something out, as this might be just a temporary fix, keep up the great work brother.

**Comment by nishad** [comment]
This issue is already fixed in https://github.com/nishad/udemy-dl/commit/ee6ecab864fc0adb5eb46d92f6a67ad370e58d27. There is nothing much to be done at this moment. Without a proper `--debug` output this issue wont be considered as valid. I'm ignoring this thread as it is misleading. @pathankp opened this issue without the mandate check lists (https://github.com/nishad/udemy-dl/blob/master/.github/ISSUE_TEMPLATE.md). I issued a warning in https://github.com/nishad/udemy-dl-windows/issues/72. But despite of that he is repeating the same thing. I am closing this issue and @pathankp will be added to `Hall of Shame`. All future issue reports from him will be ignored and closed.
