### ISSUE TITLE
[BUG] Error Not a Downloadable Course 

### ISSUE THREAD

**Issue by farazhussain2015** [nishad/udemy-dl#60]
I am getting this error , is there any solution ? 

Trying to log in ... and we're done.
ERROR: Not a downloadable course.

**Comment by mukhlesur-millon** [comment]
yes, enroll on that course.

**Comment by farazhussain2015** [comment]
thats not answer of my question ..... @mukhlesur-millon

**Comment by egadgetjnr** [comment]
Yes it is a solution. 
You're not able to download courses that you don't own.

**Comment by nishad** [comment]
All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.

Due to this policy I'm closing this thread, you can reopen this issue after making sufficient changes.
