### ISSUE TITLE
[QUESTION] Failed to get course ID

### ISSUE THREAD

**Issue by vanatomas** [nishad/udemy-dl#61]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
Getting Failed to get course ID error.
Did update, no go, did uninstall/reinstall, same thing. 
Checked for open issues, same issue closed, but without any fix resolution.
Please, assist

**Comment by arekkot** [comment]
I have the same problem. Udemy change the API for viewing courses. :(

**Comment by egadgetjnr** [comment]
What is the purchase date on the course you're trying to download?

**Comment by vanatomas** [comment]
a while back, just it got updated and I wanted to get new lectures downloaded

**Comment by nishad** [comment]
I don't think that, any of the proper issue reports got cancelled without a resolution. Issues will be closed either for violating community standards or for not including any of the mandate requirements.

This issue is already fixed, but if you are facing it, you can post the output html for --debug parameter, either here or in gist.github.com.

**Comment by vanatomas** [comment]
Hi Nishad, with all the respect, I stated that I tried to pull from repo as new install expecting issue resolved that I could not see was in other thread. 
When I try adding --debug in the request, I do get error as unrecognized arguments: --debug 
Please, advise and I will provide report

**Comment by nishad** [comment]
If you are getting unrecognised argument error, then you may not be running the latest development version of udemy-dl.

You can refer the project wiki, for getting help with updating development version.

**Comment by vanatomas** [comment]
I did what is stated in wiki to update or clean install. I am using OSx
In OS X you need to sudo installing udemy-dl or you may face some errors

sudo pip install udemy-dl

Update

In OS X you need to sudo upgrade udemy-dl

 sudo pip install --upgrade udemy-dl


Am I missing something from README file?

**Comment by nishad** [comment]
Please check the project wiki. That's not how you update a development version.

**Comment by vanatomas** [comment]
ok, I tried upgrading and also uninstall and clean install as per wiki
Getting this error
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 557, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 414, in udemy_dl
    for data in get_data_links(course_id, lecture_start, lecture_end):
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 263, in get_data_links
    course_data_len = len(course_data['results'])
KeyError: u'results'

**Comment by nishad** [comment]
Now it turned out to be another issue, you can try with a different course to see if it works.

**Comment by vanatomas** [comment]
tried another course, it worked. Any idea what can be the cause of initial one?

**Comment by nishad** [comment]
No idea :laughing: ,
`--debug` is not yet implemented for all steps, it will be available soon with https://github.com/nishad/udemy-dl/milestones/v0.2.2, then you can debug this issue by posting here, the debug json and html files.

**Comment by OnlineEdge** [comment]
getting the same "Failed to get course ID" error

Version:
udemy-dl 0.2.0

Operating System:
OSx

Notes:
Attempted with 3 paid courses (which were purchased 30 minutes prior)

**Comment by replicat0r** [comment]
@OnlineEdge 
How did you pull in the latest dev version?

I did `sudo pip install udemy-dl --ignore-installed`

which still installed udemy-dl 0.2.0. 

I am having the same issue as you are. When i tried to download, I get 

Failed to get course ID

The same command was working a couple days ago with a different course. I just bought a new course. Udemy also updated their interface and learning system. So it could be that? 

@nishad , any ideas?

**Comment by nishad** [comment]
@replicat0r, Check the project wiki for instructions.

**Comment by bilton** [comment]
Udemy has recently updated their UI

**Comment by mukhlesur-millon** [comment]
they are changing rapidly :smiley_cat:

**Comment by riteshpuj2013** [comment]
@nishad 
I have installed the latest version and error i am getting is : 
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Failed to get course ID

**Comment by mukhlesur-millon** [comment]
@riteshpuj2013 this is not about udemy-dl, google it. http://stackoverflow.com/q/29134512/6104193

**Comment by mukhlesur-millon** [comment]
this will help you with course id
`sudo python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master`

**Comment by vanatomas** [comment]
tried above, getting different error
Trying to log in ... and we're done.
Searching course id... Found: 246652
Getting course data: 1.06% [                    ] Cannot download lecture " " as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 1.59% [                    ] Cannot download lecture " " as "'NoneType' object has no attribute '__getitem__'"
Getting course data: 2.12% [                    ] Cannot download lecture " " as "'NoneType' object has no attribute '__getitem__'"

**Comment by mukhlesur-millon** [comment]
update it again @vanatomas

**Comment by alabastida** [comment]
@mukhlesur-millon I tried your update for the ID error i was getting on the course I bought, it works but it downloads some of the files and many others just get skipped leaving empty video files

**Comment by vanatomas** [comment]
@mukhlesur-millon I confirm that seeing same behaviour as @alabastida stated 
Download works, but cannot play any lectures.

**Comment by jtalb** [comment]
@vanatomas @alabastida Good to see that I'm not the only person experiencing the encoding problem. I raised this as an issue yesterday too - https://github.com/nishad/udemy-dl/issues/69.

**Comment by nishad** [comment]
@alabastida, @vanatomas, @jtalb your issue is https://github.com/nishad/udemy-dl/issues/69. So please continue with that thread, and leave this one exclusively for  `Failed to get course ID`, as the title says. 

If your comments are not in a proper thread and scattered all around, it will be difficult to track or fix. Always open new issue reports, if you are facing any different problems than the one dealing with this thread.

**Comment by elvismdev** [comment]
Works for me updating from master branch.
`python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master`

**Comment by riteshpuj2013** [comment]
@elvismdev - agreed
updating from master branch got me everything working.

**Comment by julioblas01** [comment]
works for me, only for free courses. with this:
python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master

**Comment by nishad** [comment]
@julioblas01, you can download all enrolled courses.

**Comment by julioblas01** [comment]
Thanks. You say enrolled courses like as courses That I Buy, or courses that I enrolll with a Preview?

**Comment by nishad** [comment]
@julioblas01, Please open a new thread if you wish, this issue is specifically for an error which says `Failed to get course ID`, which is not related to your comment.

**Comment by vanatomas** [comment]
@nishad all works now, ty

**Comment by jcrawford** [comment]
I am getting the Failed to get course ID error as well and i just installed fresh 0.2.0

**Comment by nishad** [comment]
@jcrawford, latest development version is `0.2.1-beta`

**Comment by AnuragChauhan07** [comment]
Thanks for this.
Will this script download attached file also given in download section ? (Sorry If I posted in wrong thread)

**Comment by AionAngel** [comment]
Im having the same issue failed to get course ID anyone could help me?

**Comment by MRMillon** [comment]
@AionAngel this kind of question doesn't deserve answer. please give the full error message and course link.

**Comment by mukhlesur-millon** [comment]
this does not exit now, please close it @vanatomas

**Comment by jcrawford** [comment]
@nishad how would one install that if it is not in pip and the instructions state to use pip for installation?  I would love to get this working again so that I could watch my courses offline....

**Comment by vanatomas** [comment]
issue is no longer present
