### ISSUE TITLE
Error:Not a downloadable course..Can we no longer download courses that we don't own??

### ISSUE THREAD

**Issue by sikandar006** [nishad/udemy-dl#63]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}
![capture](https://cloud.githubusercontent.com/assets/16998470/13984339/89e584b8-f11b-11e5-9a78-d67ff73d45a7.PNG)

**Comment by mukhlesur-millon** [comment]
no

**Comment by nishad** [comment]
Closing this thread since this issue report does not satisfy this project's mandate requirements on reporting an issue.
