### ISSUE TITLE
[BUG] Cannot download videos after the new update of udemy

### ISSUE THREAD

**Issue by vinayakvivek** [nishad/udemy-dl#66]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hi,
I'm not able to download videos after the new udemy update. I have downloaded one full course before. 
After running the command, the following is getting displayed
> Trying to log in ... and we're done.
Getting course data: 0.78% [                    ] Cannot download lecture "What does the course cover" as "'NoneType' object has no attribute '__getitem__'"

Pls check this issue.

**Comment by ChristianAE** [comment]
I experience the same error.

**Comment by mukhlesur-millon** [comment]
[BUG] Cannot download lecture "Lecture_Title" as "'NoneType' object has no attribute 'getitem'" #62

**Comment by johncy65** [comment]
same error

**Comment by mukhlesur-millon** [comment]
`python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master` this should fix your problem. please  let me know what is the result.

**Comment by vinayakvivek** [comment]
@mukhlesur-millon tried that. But output is the same after upgrading also.

**Comment by mukhlesur-millon** [comment]
course link?

**Comment by vinayakvivek** [comment]
@mukhlesur-millon https://www.udemy.com/java-the-complete-java-developer-course/

**Comment by mukhlesur-millon** [comment]
you can use `--debug`

**Comment by mukhlesur-millon** [comment]
i have made some changes. update it.
`sudo python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master`

**Comment by vinayakvivek** [comment]
@mukhlesur-millon I'm getting an output as shown(It didn't download any files). I don't know if it is an installation problem. I uninstalled the previous version and ran the command which you  gave above. Can you pls check this?

>Downloading to: /home/crossroads/home/crossroads/pro

>/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Trying to log in ... and we're done.
Searching course id... Found: 533682
Getting course data: 100.00% [....................] Done
Downloading Video: 001 Getting Started With This Course

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    318      0  0:00:01  0:00:01 --:--:--   318
Downloading Video: 002 How to Use This Section Of The Course

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    681      0 --:--:-- --:--:-- --:--:--   681
Downloading Video: 003 How To Install The Java Development Kit JDK For Windows

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    689      0 --:--:-- --:--:-- --:--:--   688
Downloading Video: 004 Install and Configure IntelliJ For Windows

>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   351  100   351    0     0    353      0 --:--:-- --:--:-- --:--:--   353
Downloading Article: 005 Free 90 Day Extended Trial of IntelliJ Ultimate Edition Now Available

>Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 662, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 557, in udemy_dl
    get_data(directory, filename, data_url, data_type)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 478, in get_data
    save_art.write(output_html)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 411: ordinal not in range(128)

**Comment by nishad** [comment]
Duplicate https://github.com/nishad/udemy-dl/issues/62
