### ISSUE TITLE
[QUESTION] Can't Play Videos?

### ISSUE THREAD

**Issue by jtalb** [nishad/udemy-dl#69]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hi all,

After installing the latest fix (27th March) I can now download videos again but I can't play them. They're in .mp4 format, but VLC and Quicktime are both saying that it can't recognise the video format. Any ideas?

Thanks a lot!

**Comment by mukhlesur-millon** [comment]
these were not downloaded. these all are text file. i fixed that. but by watching some course i thought udemy update it and i have deleted my downloader. it will be fixed latter.

**Comment by kmes** [comment]
All videos are 351 byte. if you open one video with text editor, their content is: 

<HTML><HEAD>
<TITLE>401 Authorization Required</TITLE>
</HEAD>
<BODY>
<H1>Authorization Required</H1>
This server could not verify that you
are authorized to access the document you
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.<P>
</BODY></HTML>

**Comment by OnlineEdge** [comment]
My --debug got exactly the same error as above (if that assists at all)

**Comment by mukhlesur-millon** [comment]
i have made a change. please test it
`sudo python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/maste`

**Comment by OnlineEdge** [comment]
`sudo python -m pip install --upgrade https://github.com/mukhlesur-millon/udemy-dl/zipball/master`

**Comment by jtalb** [comment]
@mukhlesur-millon Just updated and it downloaded the course perfectly. Videos are great quality too. Thanks for fixing!
