### ISSUE TITLE
[BUG] ERROR: Not a downloadable course

### ISSUE THREAD

**Issue by cirrus1** [nishad/udemy-dl#73]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [x] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
 i tried to download a course but this is the error showed
ERROR: Not a downloadable course

this is the log 
{C:\>udemy-dl -u xxxxxx@gmail.com -p xxxxx https://www.u
demy.com/xxx/
Downloading to: C:\Users\xxx\xxxxxxxxx

Trying to log in ... and we're done.
Searching course id... Found: 7093xx
ERROR: Not a downloadable course.}

**Comment by nishad** [comment]
Not all courses are downloadable. It is not a error.
