### ISSUE TITLE
udemy error

### ISSUE THREAD

**Issue by jaan143** [nishad/udemy-dl#77]
hi 
is this working fine now for everyone ?
i am still getting error evan i installed udemy in python but via window powershell i got also error

PS C:\Users\vicky> udemy-dl -u *****@gmail.com -p ***** https://www.udemy.com/job-interview-mastery/
udemy-dl.py : The term 'udemy-dl.py' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ udemy-dl -u *****@gmail.com -p ***** https://www.udemy.co ...
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (udemy-dl.py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\vicky>

**Comment by nishad** [comment]
**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can reopen this issue after making sufficient changes.
