### ISSUE TITLE
Draft mode course asking 'Enrollement', Not able to download

### ISSUE THREAD

**Issue by AnuragChauhan07** [nishad/udemy-dl#79]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

==================================
One course is in draft mode, I am trying with this script. (Enrolled in this course.)

Getting this
----
```
Downloading to: E:\draft

Trying to log in ... and we're done.
Please Enroll in this course
```
----
==================================

**Comment by nishad** [comment]
**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can reopen this issue after making sufficient changes.

**Comment by AnuragChauhan07** [comment]
I am raising issue first time on GitHub, can you help me in this.

**Comment by nishad** [comment]
**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can reopen this issue after making sufficient changes.

**Comment by AnuragChauhan07** [comment]
How can i reopen it again ?

**Comment by nishad** [comment]
You can reopen this issue after making sufficient changes.

**Comment by AnuragChauhan07** [comment]
I checked all check boxes and added prefix also. but did find any button to reopen it. Can you help me ?

**Comment by nishad** [comment]
This is already discussed in https://github.com/nishad/udemy-dl/issues/62#issuecomment-203041152. you can refer answers given there. If you still got some confusion please comment here, if valid I'll reopen this thread.

**Comment by AnuragChauhan07** [comment]
Thanks, I didn't check closed threads, next time I won't do this. Checking #62 now.

**Comment by nishad** [comment]
https://github.com/nishad/udemy-dl/issues/62, is not closed, and you checked yes for item 4 in checklist without even reading ? Shame on you :rage: 

- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)

**Comment by AnuragChauhan07** [comment]
Sorry for this again. I am new on this I created my account a long time ago but don't know anything about it(How to use GitHub). So forgive me for this mistake.
