### ISSUE TITLE
Just get the link

### ISSUE THREAD

**Issue by LucasRoot** [nishad/udemy-dl#8]
Hey, I just want to get the link to download the videos.
And after I will download each with my own download manager.

Thanks

**Comment by nishad** [comment]
Dear @LucasRoot,
As per the current strategy of the project, I'll be providing only bug fixes and patches for the existing `udemy-dl` python package. I'm not planning to implement any new features or enhancements for the time being.

However, for windows, you can use https://github.com/nishad/udemy-dl-windows/, which got extended support for using other download managers like `aria2c`. which is faster than most of the conventional download managers with resume support

:sake: kanpai :)
