### ISSUE TITLE
[BUG] fails wit latest slugify

### ISSUE THREAD

**Issue by zabbal** [nishad/udemy-dl#80]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Fails with latest slugify with following error:
```
...udemy_dl.py, line 30, in <module>
    from slugify import slugify, SLUG_OK
ImportError: cannot import name SLUG_OK
```

**Comment by nishad** [comment]
Have you tried it install via pip ? There are couple of different slugify packages, all got slugify as it's module name.

For example https://github.com/un33k/python-slugify and  https://github.com/dimka665/awesome-slugify. But this project uses https://github.com/mozilla/unicode-slugify.

See requirements file for this package, https://github.com/nishad/udemy-dl/blob/master/requirements.txt

You may need to uninstall any other slugify package and install this one to get it working.

**Comment by zabbal** [comment]
Doh! My bad, sorry. Thanks for explanation.
