### ISSUE TITLE
[PROPOSAL] support newer requests version

### ISSUE THREAD

**Issue by zabbal** [nishad/udemy-dl#82]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
Project's requirements explicitly mention requests' module version 2.3.0 which is pretty old. Would be nice to get udemy-dl working with newer versions.

Btw, it might make sense to move requirements.txt inot readme.md to increase visibility.

**Comment by nishad** [comment]
You can try with newer version of `requests`, and if it works issue a pull request with modifications.

PS: Check lists should be like `[x]` there should not be any space between `[` and `x`. Please edit your issue to fix that.

**Comment by nishad** [comment]
`requirements.txt` is for `pip`. If someone is installing this package manually, they should be aware of it. You can edit project wiki to create a page for manual installation instructions.

**Comment by zabbal** [comment]
With 2.7.0 it fails due to (it seems) api change:
  File "/usr/lib/python2.7/dist-packages/urllib3/util/response.py", line 49, in assert_header_parsing
    if not isinstance(headers, httplib.HTTPMessage):
AttributeError: 'module' object has no attribute 'HTTPMessage'

**Comment by MRMillon** [comment]
please upgrade udemy-dl:
`sudo python -m pip install https://github.com/nishad/udemy-dl/zipball/master -U`

this should fix your problem

**Comment by mukhlesur-millon** [comment]
as this issue is not about `udemy-dl`, please close it. upgrading `future` package to `0.15.2` will fix your problem. or upgrade udemy-dl as i have comment above
