### ISSUE TITLE
Error (TypeError)

### ISSUE THREAD

**Issue by gnolasco92** [nishad/udemy-dl#83]
[QUESTION]
**[QUESTION]**.

Guy's I'm having the following problem when I try to download a  couse from Udemy

"Traceback (most recent call last):
  File "<string>", line 374, in <module>
  File "<string>", line 370, in main
  File "<string>", line 290, in udemy_dl
  File "<string>", line 216, in get_video_links
TypeError: string indices must be integers"

**Comment by MRMillon** [comment]
course link?

**Comment by MRMillon** [comment]
**In raising this issue, I confirm the following:**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows:**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

@gnolasco92 issues should look like this and you must follow the above.

- title should be prefixed with one the following

  - [BUG]

  - [PROPOSAL]

  - [QUESTION]

here will be complete description of your error
