### ISSUE TITLE
[QUESTION] resume download

### ISSUE THREAD

**Issue by vanatomas** [nishad/udemy-dl#86]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

My question:
If download was interrupted or new lectures were added to the course, udemy-dl does not offer to resume from last known place or add missing new/missing lecture? 

I remember at one point that there was such option, was it taken away?

I get this error, when  I try to update course with new lecture. 
```
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 688, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 578, in udemy_dl
    get_data(directory, filename, data_url, data_type)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 491, in get_data
    get_video(link, filename)
  File "/Library/Python/2.7/site-packages/udemy_dl/udemy_dl.py", line 469, in get_video
    download(link, filename, update_progress, downloader)
  File "/Library/Python/2.7/site-packages/udemy_dl/download.py", line 55, in download
    raise DLException('Failed to download this lecture')
udemy_dl.download.DLException: Failed to download this lecture
```

**Comment by mukhlesur-millon** [comment]
install `aria2c`
`sudo apt-get install aria2`

**Comment by vanatomas** [comment]
@mukhlesur-millon thank you for explanation, and that what I saw as error for aria. I am on Mac, so did this - brew install aria2 and all seems to be good.

**Comment by mukhlesur-millon** [comment]
please use `-d curl` there is some problem with aria2.
