### ISSUE TITLE
Failed to fetch token.

### ISSUE THREAD

**Issue by hauses123** [nishad/udemy-dl#89]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [+] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [+] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [+] I have checked that the issue I'm posting isn't already reported.
- [+] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [+] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [+] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{When i try to download a course it says "Failed to fetch token" I don't know what's the problem, i was surfing the net i saw a solution, "download the latest udemy" And yeah i did download the latest udemy but it still wont let me download any course, it used to be fine.}

**Comment by mukhlesur-millon** [comment]
please remove spaces in `[ ]` 
![img_20160410_084031](https://cloud.githubusercontent.com/assets/12371264/14407820/2a537b00-fef8-11e5-811e-6a37ef21c0d7.JPG)

change your title to `[BUG] Failed to fetch token`.

have you upgraded for [here] (https://github.com/nishad/udemy-dl/wiki/Installing-development-version)?

**Comment by shitosmagdi** [comment]
please i dont know what to do cause i barely followed the steps .... and it doesnt work 
" couldnt fetch token ! " appears 
please help

**Comment by nishad** [comment]
@hauses123,

**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
