### ISSUE TITLE
request 

### ISSUE THREAD

**Issue by Darkcast** [nishad/udemy-dl#9]
can you create a way to download from a list of courses ?
Thanks

**Comment by nishad** [comment]
This is possible via shell script in linux  and mac or batch file in windows. So I don't think that, extending `udemy-dl` with this option is important. 

For example in shell script 

```bash
#!/bin/sh
while read f; do
    udemy-dl -u user@domain.com -p $ecRe7w0rd "$f"
done < list.txt
```
In Windows Batch file

```batch
for /f %%i in (list.txt) do udemy-dl -u user@domain.com -p $ecRe7w0rd %%i
```

With a `list.txt` like

```
https://www.udemy.com/COURSE_NAME_01
https://www.udemy.com/COURSE_NAME_02
https://www.udemy.com/COURSE_NAME_03
https://www.udemy.com/COURSE_NAME_04
```
