### ISSUE TITLE
[BUG] Failed to Get Course ID

### ISSUE THREAD

**Issue by Gemsmith** [nishad/udemy-dl#95]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Getting Failed to get course ID error.
Updated Python to 3.5.1
Updated "udemy-dl" via command
`python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master,` 
Updated pip.
`using a command shown in cmd after the above update`
Checked for open issues, same issue closed, but without any fix.
Please, Assist.

**Comment by nishad** [comment]
```
python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master,
```

This should be without trailing `,` 
```
python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master
```

If this is done, post the output of

```
udemy-dl -v
```

**Comment by Gemsmith** [comment]
It returns 
udemy-dl.exe 2.0.1

**Comment by nishad** [comment]
This project doesn't got any `.exe` or `2.x.x` releases, Current expected output of `udemy-dl -v' is `0.2.1-beta`. Something is wrong with your issue report.

**Comment by Gemsmith** [comment]
Hi Nishad, Can I correct this by using update.cmd? Or should I redownload udemy-dl and then run update?
PS.: I have udemy-dl folder in the base of my Windows drive (C:/)

**Comment by nishad** [comment]
This project doesn't got any `update.cmd` and `pip install` will never keep `udemy-dl` folder in the base of your windows drive. 

This issue report seems to be invalid.

**Comment by Gemsmith** [comment]
Sorry I posted the bug in your udemy-dl, while I have the udemy-dl-windows, is it possible to move this bug over there? Or should I post new issue over there?

**Comment by nishad** [comment]
This project is independent from `udemy-dl-windows`, but  `udemy-dl-windows` depends on this project. Due to this reason both this projects are treated and maintained separately. This issue is invalid for this project and I'm closing this thread.
