### ISSUE TITLE
OSX: Couldn't fetch token

### ISSUE THREAD

**Issue by davidvb** [nishad/udemy-dl#96]
installation of dependencies all succeeded, but upon download the script returns this error: "Couldn't fetch token"
I tried both call methods but without difference.. is it a Bug or something I should do differently?

**Comment by nishad** [comment]
**All issues should contain mandatory check lists and proper prefix for the subject line. Issues reported without checklists or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
