### ISSUE TITLE
[BUG] Failed to get Course ID on Windows 2.0.1

### ISSUE THREAD

**Issue by MayurAgarkar** [nishad/udemy-dl#97]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [x] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Just throws the states erro message at the end and never downloads anything.
Any fix for this ?

**Comment by nishad** [comment]
This Issue doesn't got any relation with this project.

**Comment by chrisfknpadilla** [comment]
I'm also coming across the same problem, although I'm not using Windows. 2.0.1

**Comment by BattlestarPegasus** [comment]
Same here.  Failed to get Course ID

**Comment by dwaynekuan** [comment]
same here.

**Comment by davidnightsoul** [comment]
Same here. Failed to get course ID

**Comment by filipealonso** [comment]
+1

**Comment by nishad** [comment]
As I've mentioned in the previous comment, This issue got nothing to do with this project. This project is platform independent and there isn't yet a ` 2.0.1` release.
